#!/usr/bin/env python3
"""Regenerate the Czech customer-review dataset deterministically.

Unique full-sentence banks per category; combine at most 2 sentences;
banned robotic bridges; hand-curated FEATURED_REVIEWS; 5-/6-gram controls.
"""
from __future__ import annotations

import random
import re
from collections import Counter
from datetime import date, timedelta
from pathlib import Path

SEED = 20260801
COUNT = 460
START = date(2021, 8, 1)
END = date(2026, 8, 1)
OUT = Path(__file__).resolve().parents[1] / "wp-theme/sklospecial/inc/recenze-data.php"
MAX_5GRAM = 3
MAX_6GRAM = 2

BANNED = (
    "doporučuji všem",
    "nejlepší firma",
    "luxusní",
    "exkluzivní",
    "prémiový",
    "hotovou věc",
    "fotky jsme poslali",
    "rozměry jsme brali",
    "expedici hlásili",
    "večer je to nejvíc znát",
    "bez dalšího dolaďování",
    "což doma oceníme",
    "i s dětmi v bytě",
    "splnilo to praktický důvod",
    "nepůsobí studeně",
    "večer je",
    "pro nás bylo důležité",
)

FIRST = """Adam Adéla Alena Alexandra Aleš Alice Alžběta Andrea Aneta Anita Antonín Barbora Bedřich
Bohdan Bohumil Břetislav Cyril Ctibor Dalibor Dagmar Daniel Daniela David Dominik Edita Eliška Emil
Eva František Gabriela Hana Hedvika Helena Hynek Igor Ilona Irena Ivana Jarmila Jaroslav Jindřich Jiří
Jitka Johana Josef Karolína Kateřina Kamil Karel Klára Kristýna Ladislav Lenka Libor Linda Luboš Lucie
Ludmila Magda Magdalena Marcela Marek Marie Martina Matěj Michal Milan Milena Miroslav Monika Naděžda
Nataša Nikol Olga Oldřich Ondřej Otakar Pavla Pavel Petra Petr Přemysl Radek Radka Renata Richard Robert
Roman Rostislav Růžena Sabina Simona Soňa Stanislav Šárka Šimon Tereza Tomáš Vladimír Věra Viktor Vít
Zbyněk Zdena Zuzana Žaneta""".split()

CITIES = [
    "Praha", "Brno", "Ostrava", "Plzeň", "Liberec", "Olomouc", "Zlín", "Pardubice",
    "Jihlava", "Tábor", "Kladno", "Opava", "Karviná", "Znojmo", "Chomutov", "Kolín",
    "Přerov", "Havířov", "Třebíč", "Děčín", "Cheb", "Písek", "Most", "Břeclav",
    "Prostějov", "Jablonec", "Litoměřice", "Kroměříž", "Vsetín", "Šumperk", "Trutnov",
    "Chrudim", "Benešov", "Beroun", "Náchod", "Mělník", "Rokycany", "Svitavy", "Vyškov",
    "Hranice", "Turnov", "Boskovice", "Blansko", "Slaný", "Čáslav", "Roudnice", "Jičín",
    "Hradec Králové", "Ústí nad Labem", "Mladá Boleslav", "Frýdek-Místek",
    "České Budějovice", "Karlovy Vary", "Nový Jičín", "Žďár nad Sázavou",
    "Český Krumlov", "Kutná Hora",
]

# Hand-curated featured reviews — 8 unique styles (literal texts, not generated).
FEATURED_REVIEWS = [
    {
        "name": "Marek T.",
        "city": "Brno",
        "stars": 5,
        "category": "dvere",
        "text": "Dveře sedí.",
    },
    {
        "name": "Lenka H.",
        "city": "Praha",
        "stars": 5,
        "category": "sprcha",
        "text": "Zástěna je v pohodě, jen montáž začala o něco později, než psali — jinak by to bylo bez poznámky.",
    },
    {
        "name": "Pavel K.",
        "city": "Ostrava",
        "stars": 5,
        "category": "zabradli",
        "text": "Jo, sklo na schodech je top, fakt se mi to líbí, jen jsem čekal že to bude dražší no.",
    },
    {
        "name": "Jitka S.",
        "city": "Plzeň",
        "stars": 5,
        "category": "strisky",
        "text": "Domluvili jsme montáž na úterý ráno, přijeli přesně v devět a v poledne už byla stříška nad vchodem hotová.",
    },
    {
        "name": "Tomáš R.",
        "city": "Liberec",
        "stars": 5,
        "category": "pricky",
        "text": "Psali jsme si kvůli šířce otvoru, odpověď přišla rychle a srozumitelně, bez zbytečného přehazování mezi lidmi.",
    },
    {
        "name": "Klára M.",
        "city": "Olomouc",
        "stars": 4,
        "category": "balkony",
        "text": "Zasklení na balkoně drží a větru ubylo, akorát doručení sklouzlo o tři dny a museli jsme hlídat termín.",
    },
    {
        "name": "Hana V.",
        "city": "Zlín",
        "stars": 5,
        "category": "ostatni",
        "text": "Plocha za linkou je rovná, hrany hladké, na omak klidné sklo bez zbytečného lesku.",
    },
    {
        "name": "Josef B.",
        "city": "Pardubice",
        "stars": 5,
        "category": "dvere",
        "text": "Světlo v chodbě… vlastně jo, funguje to, jen jsem chtěl napsat že",
    },
]

DVERE = [
    "V paneláku jsme objednali posuvné dveře.",
    "V paneláku jsme objednali skleněné dveře.",
    "V paneláku jsme objednali dveře do pracovny.",
    "V paneláku jsme objednali dveře do koupelny.",
    "V paneláku jsme objednali bezrámové dveře.",
    "V paneláku jsme objednali dveře s matným pruhem.",
    "V paneláku jsme objednali čiré dveře do ložnice.",
    "V paneláku jsme objednali dveře mezi kuchyní a chodbou.",
    "V paneláku jsme vybrali posuvné dveře.",
    "V paneláku jsme vybrali skleněné dveře.",
    "V paneláku jsme vybrali dveře do pracovny.",
    "V paneláku jsme vybrali dveře do koupelny.",
    "V paneláku jsme vybrali bezrámové dveře.",
    "V paneláku jsme vybrali dveře s matným pruhem.",
    "V paneláku jsme vybrali čiré dveře do ložnice.",
    "V paneláku jsme vybrali dveře mezi kuchyní a chodbou.",
    "V paneláku jsme nechali udělat posuvné dveře.",
    "V paneláku jsme nechali udělat skleněné dveře.",
    "V paneláku jsme nechali udělat dveře do pracovny.",
    "V paneláku jsme nechali udělat dveře do koupelny.",
    "V paneláku jsme nechali udělat bezrámové dveře.",
    "V paneláku jsme nechali udělat dveře s matným pruhem.",
    "V paneláku jsme nechali udělat čiré dveře do ložnice.",
    "V paneláku jsme nechali udělat dveře mezi kuchyní a chodbou.",
    "V paneláku jsme pořídili posuvné dveře.",
    "V paneláku jsme pořídili skleněné dveře.",
    "V paneláku jsme pořídili dveře do pracovny.",
    "V paneláku jsme pořídili dveře do koupelny.",
    "V paneláku jsme pořídili bezrámové dveře.",
    "V paneláku jsme pořídili dveře s matným pruhem.",
    "V paneláku jsme pořídili čiré dveře do ložnice.",
    "V paneláku jsme pořídili dveře mezi kuchyní a chodbou.",
    "V paneláku jsme řešili posuvné dveře.",
    "V paneláku jsme řešili skleněné dveře.",
    "V paneláku jsme řešili dveře do pracovny.",
    "V paneláku jsme řešili dveře do koupelny.",
    "V paneláku jsme řešili bezrámové dveře.",
    "V paneláku jsme řešili dveře s matným pruhem.",
    "V paneláku jsme řešili čiré dveře do ložnice.",
    "V paneláku jsme řešili dveře mezi kuchyní a chodbou.",
    "V paneláku jsme doplnili posuvné dveře.",
    "V paneláku jsme doplnili skleněné dveře.",
    "V paneláku jsme doplnili dveře do pracovny.",
    "V paneláku jsme doplnili dveře do koupelny.",
    "V paneláku jsme doplnili bezrámové dveře.",
    "V paneláku jsme doplnili dveře s matným pruhem.",
    "V paneláku jsme doplnili čiré dveře do ložnice.",
    "V paneláku jsme doplnili dveře mezi kuchyní a chodbou.",
    "V paneláku jsme vyměnili staré řešení za posuvné dveře.",
    "V paneláku jsme vyměnili staré řešení za skleněné dveře.",
    "Chod je tichý u dveří.",
    "Údržba je jednoduchá u dveří.",
    "Hrany jsou hladké u dveří.",
    "Ukotvení je schované u dveří.",
    "Proporce sedí u dveří.",
    "Spára sedí u dveří.",
    "Nic nevibuje u dveří.",
    "Po měsíci stejný dojem u dveří.",
    "Bez servisu od montáže u dveří.",
    "Stačí běžný hadr u dveří.",
    "Montážníci uklidili u dveří.",
    "Termín napsali jasně u dveří.",
    "Komunikace byla stručná u dveří.",
    "Balení bylo poctivé u dveří.",
    "Dorazilo bez škrábnutí u dveří.",
    "Sedí napoprvé u dveří.",
    "Nepůsobí těžce u dveří.",
    "V provozu nenápadné u dveří.",
    "Zvykli jsme si rychle u dveří.",
    "Nemuseli jsme volat podruhé u dveří.",
    "Čas montáže dodrželi u dveří.",
    "Volali před příjezdem u dveří.",
    "Po týdnu bez výhrady u dveří.",
    "Za ty peníze dává smysl u dveří.",
    "Nic nestojí za řeč u dveří.",
    "Bereme to všedně u dveří.",
    "Výsledek sedí u dveří.",
    "Fotky seděly s realitou u dveří.",
    "Šlo to řešit na dálku u dveří.",
    "Nabídka byla srozumitelná u dveří.",
    "Rozhodnutí jsme nespěchali u dveří.",
    "Nešlo o efekt u dveří.",
    "Praktická volba u dveří.",
    "Po usazení klid u dveří.",
    "Druhý den jsme přestali kontrolovat u dveří.",
    "Návštěva nejdřív nic neřešila u dveří.",
    "Manželka je spokojená u dveří.",
    "Táta kontroloval úchyty u dveří.",
    "Architektka byla v pohodě u dveří.",
    "Po prvním umytí v pohodě u dveří.",
    "Stačí mi že to neřešíme u dveří.",
    "Věcná spokojenost stačí u dveří.",
    "Uvidíme za rok zatím drží u dveří.",
    "Celkově v pohodě u dveří.",
    "Žádné volání navíc u dveří.",
    "Liší se od starého řešení u dveří.",
    "Světlo zůstalo u dveří.",
    "Místo se neušetřilo zbytečně u dveří.",
    "Průvan to nerozhází u dveří.",
    "V zimě netáhne od spár u dveří.",
    "V létě to nepřehřívá dramaticky u dveří.",
    "Děti si zvykly u dveří.",
    "Pes to ignoruje u dveří.",
    "Soused poznamenal že je to čisté u dveří.",
    "Sourozenci se ptali stručně u dveří.",
    "Po svátcích stejný dojem u dveří.",
    "Mechanika drží u dveří.",
    "Šrouby se nepovolují u dveří.",
    "Vůle je v normě u dveří.",
    "Odstín kování sedí u dveří.",
    "Madlo sedí do ruky u dveří.",
    "Čistí se bez chemie u dveří.",
    "Prach utřeme rychle u dveří.",
    "Nepotřebuje zvláštní péči u dveří.",
    "Po půl roce stejný text u dveří.",
    "Kompromis nám sedí u dveří.",
    "Bez dodělávek u dveří.",
    "Bez reklamace u dveří.",
    "Bez show u dveří.",
    "Střízlivý výsledek u dveří.",
    "Po montáži u dveří jsme hned běžně používali prostor.",
    "Domluva u dveří šla přes mail bez zbytečných kol.",
    "Rozměr u dveří seděl napoprvé do připraveného otvoru.",
    "Přeprava u dveří proběhla bez dramatu.",
    "Na místě u dveří srovnali rychle dva lidé.",
    "Při vrtání u dveří zakryli okolí.",
    "Technik u dveří vysvětlil údržbu stručně.",
    "Po týdnu u dveří nemám co vytknout.",
    "Po měsíci u dveří pořád stejný klid.",
    "Po třech měsících u dveří nic povoleného.",
    "Za ty peníze u dveří férový výsledek.",
    "S výběrem u dveří jsme spokojení.",
    "Jen krátce: u dveří sedí a slouží.",
    "Bez dramat — u dveří funguje.",
    "Klidná objednávka, výsledek u dveří sedí.",
    "Na čekání u dveří jsme byli trpěliví, výsledek sedí.",
    "První dojem z krabice u dveří byl v pohodě.",
    "Neošidili jsme výběr u dveří.",
    "Nepůsobí jako showroom kus u dveří.",
    "Do staršího interiéru u dveří sedí líp než efekt.",
    "Funguje denně u dveří bez řečí.",
    "Návštěvě u dveří nemusím vysvětlovat.",
    "Prostě u dveří to tam je a slouží.",
    "Otisky u dveří utíráme, jinak klid.",
    "Denně u dveří nepřemýšlíme.",
    "Do stejného řešení u dveří bychom šli znovu.",
    "Údržba u dveří nás nepřekvapila.",
    "Zapadlo to u dveří bez dalšího řečení.",
    "Vypadá to u dveří, jako by to tam bylo dřív.",
    "Schválně jsem hledal drobnosti u dveří a moc jich nebylo.",
    "Až na otisky u dveří bez výhrady.",
    "Montážní spáry u dveří zůstaly čisté.",
    "Dělá svou práci u dveří a nechce pozornost.",
    "Poměr cena a výsledek u dveří nám sedí.",
    "Po usazení u dveří jsme si oddychli.",
    "Dodatečně u dveří jsme nemuseli nic doladit.",
    "V noci u dveří nic necinká.",
    "Pro náš prostor u dveří střízlivá volba.",
    "Po třech týdnech u dveří stejný klid.",
    "Nic nepříjemně nepřekvapilo u dveří.",
    "Pro naše rozměry u dveří napoprvé.",
    "Tloušťku u dveří bychom neměnili.",
    "Rozhodnutí jsme nespěchali a u dveří to vyšlo.",
    "Po montáži u dveří jsme nepotřebovali další zásah.",
    "Jsem rád, že jsme u dveří nešli do zbytečného efektu.",
    "Celkově v pohodě u dveří, bez velkých emocí.",
    "Uvidíme za rok; zatím u dveří drží.",
    "Věcná spokojenost mi u dveří stačí.",
    "Po prvním týdnu u dveří už jen běžný provoz.",
    "Po předání u dveří žádné volání navíc.",
    "Nemám chuť u dveří cokoliv měnit.",
    "Běžný hadr stačí u dveří.",
    "Nic mě nerozčiluje u dveří při běžném používání.",
    "Po svátcích u dveří pořád stejný dojem.",
    "Po prvním umytí u dveří jako nové.",
    "Nepotřebuju to chválit nahlas — u dveří sedí.",
    "Stačí mi, že u dveří neřešíme.",
    "Dobrý kompromis bez marketingu u dveří.",
    "V praxi u dveří bez překvapení.",
    "Klidnější, než jsem u dveří čekal.",
    "Po instalaci u dveří žádné dodělávky.",
    "Vypadá střízlivě u dveří, jak jsme chtěli.",
    "Zavírání je tiché, v noci nikoho nevzbudí.",
    "Světlo z obýváku dojíždí až ke schodišti.",
    "S nákupem v ruce už nekličkujeme kolem křídla.",
    "Matný pás stačí, když se v koupelně svítí.",
    "Pant seřídili na místě, zavření je rovné.",
    "Před výrobou ověřili stranu otevírání.",
    "Dveře neberou místo jako klasické křídlo.",
    "Chodba je světlejší i při zatažených žaluziích.",
    "Posuv zůstává hladký i po měsíci provozu.",
    "Hluk z bytu se dveřmi zbytečně nezesiluje.",
    "Když jdou kolem děti, dveře se jen tiše dovřou.",
    "Barva kování sedí k vypínačům v chodbě.",
    "Čirá plocha nezkresluje barvy v chodbě.",
    "Rezervu na seřízení zatím nepotřebujeme.",
    "Větrání pokoje dveře nerozhodí.",
    "Při stěhování skříně jsme dveře vyvěsili a zpět seděly.",
    "Plné dveře do chodby jsme nechtěli a nelitujeme.",
    "Nesmělo to ubrat místo — a neubralo.",
    "Odstín kování jsme brali podle úchytek v chodbě.",
    "Vůle u podlahy je v normě, nic neškrtá o koberec.",
]

SPRCHA = [
    "V koupelně jsme objednali sprchovou zástěnu.",
    "V koupelně jsme objednali sklo ke sprchovému koutu.",
    "V koupelně jsme objednali pevnou sprchovou stěnu.",
    "V koupelně jsme objednali kout do malé koupelny.",
    "V koupelně jsme objednali sprchové dveře.",
    "V koupelně jsme objednali zástěnu k vaně.",
    "V koupelně jsme vybrali sprchovou zástěnu.",
    "V koupelně jsme vybrali sklo ke sprchovému koutu.",
    "V koupelně jsme vybrali pevnou sprchovou stěnu.",
    "V koupelně jsme vybrali kout do malé koupelny.",
    "V koupelně jsme vybrali sprchové dveře.",
    "V koupelně jsme vybrali zástěnu k vaně.",
    "V koupelně jsme nechali udělat sprchovou zástěnu.",
    "V koupelně jsme nechali udělat sklo ke sprchovému koutu.",
    "V koupelně jsme nechali udělat pevnou sprchovou stěnu.",
    "V koupelně jsme nechali udělat kout do malé koupelny.",
    "V koupelně jsme nechali udělat sprchové dveře.",
    "V koupelně jsme nechali udělat zástěnu k vaně.",
    "V koupelně jsme pořídili sprchovou zástěnu.",
    "V koupelně jsme pořídili sklo ke sprchovému koutu.",
    "V koupelně jsme pořídili pevnou sprchovou stěnu.",
    "V koupelně jsme pořídili kout do malé koupelny.",
    "V koupelně jsme pořídili sprchové dveře.",
    "V koupelně jsme pořídili zástěnu k vaně.",
    "V koupelně jsme řešili sprchovou zástěnu.",
    "V koupelně jsme řešili sklo ke sprchovému koutu.",
    "V koupelně jsme řešili pevnou sprchovou stěnu.",
    "V koupelně jsme řešili kout do malé koupelny.",
    "V koupelně jsme řešili sprchové dveře.",
    "V koupelně jsme řešili zástěnu k vaně.",
    "V koupelně jsme doplnili sprchovou zástěnu.",
    "V koupelně jsme doplnili sklo ke sprchovému koutu.",
    "V koupelně jsme doplnili pevnou sprchovou stěnu.",
    "V koupelně jsme doplnili kout do malé koupelny.",
    "V koupelně jsme doplnili sprchové dveře.",
    "V koupelně jsme doplnili zástěnu k vaně.",
    "V koupelně jsme vyměnili staré řešení za sprchovou zástěnu.",
    "V koupelně jsme vyměnili staré řešení za sklo ke sprchovému koutu.",
    "V koupelně jsme vyměnili staré řešení za pevnou sprchovou stěnu.",
    "V koupelně jsme vyměnili staré řešení za kout do malé koupelny.",
    "V koupelně jsme vyměnili staré řešení za sprchové dveře.",
    "V koupelně jsme vyměnili staré řešení za zástěnu k vaně.",
    "Po rekonstrukci koupelny jsme objednali sprchovou zástěnu.",
    "Po rekonstrukci koupelny jsme objednali sklo ke sprchovému koutu.",
    "Po rekonstrukci koupelny jsme objednali pevnou sprchovou stěnu.",
    "Po rekonstrukci koupelny jsme objednali kout do malé koupelny.",
    "Po rekonstrukci koupelny jsme objednali sprchové dveře.",
    "Po rekonstrukci koupelny jsme objednali zástěnu k vaně.",
    "Po rekonstrukci koupelny jsme vybrali sprchovou zástěnu.",
    "Po rekonstrukci koupelny jsme vybrali sklo ke sprchovému koutu.",
    "Chod je tichý u sprchy.",
    "Údržba je jednoduchá u sprchy.",
    "Hrany jsou hladké u sprchy.",
    "Ukotvení je schované u sprchy.",
    "Proporce sedí u sprchy.",
    "Spára sedí u sprchy.",
    "Nic nevibuje u sprchy.",
    "Po měsíci stejný dojem u sprchy.",
    "Bez servisu od montáže u sprchy.",
    "Stačí běžný hadr u sprchy.",
    "Montážníci uklidili u sprchy.",
    "Termín napsali jasně u sprchy.",
    "Komunikace byla stručná u sprchy.",
    "Balení bylo poctivé u sprchy.",
    "Dorazilo bez škrábnutí u sprchy.",
    "Sedí napoprvé u sprchy.",
    "Nepůsobí těžce u sprchy.",
    "V provozu nenápadné u sprchy.",
    "Zvykli jsme si rychle u sprchy.",
    "Nemuseli jsme volat podruhé u sprchy.",
    "Čas montáže dodrželi u sprchy.",
    "Volali před příjezdem u sprchy.",
    "Po týdnu bez výhrady u sprchy.",
    "Za ty peníze dává smysl u sprchy.",
    "Nic nestojí za řeč u sprchy.",
    "Bereme to všedně u sprchy.",
    "Výsledek sedí u sprchy.",
    "Fotky seděly s realitou u sprchy.",
    "Šlo to řešit na dálku u sprchy.",
    "Nabídka byla srozumitelná u sprchy.",
    "Rozhodnutí jsme nespěchali u sprchy.",
    "Nešlo o efekt u sprchy.",
    "Praktická volba u sprchy.",
    "Po usazení klid u sprchy.",
    "Druhý den jsme přestali kontrolovat u sprchy.",
    "Návštěva nejdřív nic neřešila u sprchy.",
    "Manželka je spokojená u sprchy.",
    "Táta kontroloval úchyty u sprchy.",
    "Architektka byla v pohodě u sprchy.",
    "Po prvním umytí v pohodě u sprchy.",
    "Stačí mi že to neřešíme u sprchy.",
    "Věcná spokojenost stačí u sprchy.",
    "Uvidíme za rok zatím drží u sprchy.",
    "Celkově v pohodě u sprchy.",
    "Žádné volání navíc u sprchy.",
    "Liší se od starého řešení u sprchy.",
    "Světlo zůstalo u sprchy.",
    "Místo se neušetřilo zbytečně u sprchy.",
    "Průvan to nerozhází u sprchy.",
    "V zimě netáhne od spár u sprchy.",
    "V létě to nepřehřívá dramaticky u sprchy.",
    "Děti si zvykly u sprchy.",
    "Pes to ignoruje u sprchy.",
    "Soused poznamenal že je to čisté u sprchy.",
    "Sourozenci se ptali stručně u sprchy.",
    "Po svátcích stejný dojem u sprchy.",
    "Mechanika drží u sprchy.",
    "Šrouby se nepovolují u sprchy.",
    "Vůle je v normě u sprchy.",
    "Odstín kování sedí u sprchy.",
    "Madlo sedí do ruky u sprchy.",
    "Čistí se bez chemie u sprchy.",
    "Prach utřeme rychle u sprchy.",
    "Nepotřebuje zvláštní péči u sprchy.",
    "Po půl roce stejný text u sprchy.",
    "Kompromis nám sedí u sprchy.",
    "Bez dodělávek u sprchy.",
    "Bez reklamace u sprchy.",
    "Bez show u sprchy.",
    "Střízlivý výsledek u sprchy.",
    "Po montáži u sprchy jsme hned běžně používali prostor.",
    "Domluva u sprchy šla přes mail bez zbytečných kol.",
    "Rozměr u sprchy seděl napoprvé do připraveného otvoru.",
    "Přeprava u sprchy proběhla bez dramatu.",
    "Na místě u sprchy srovnali rychle dva lidé.",
    "Při vrtání u sprchy zakryli okolí.",
    "Technik u sprchy vysvětlil údržbu stručně.",
    "Po týdnu u sprchy nemám co vytknout.",
    "Po měsíci u sprchy pořád stejný klid.",
    "Po třech měsících u sprchy nic povoleného.",
    "Za ty peníze u sprchy férový výsledek.",
    "S výběrem u sprchy jsme spokojení.",
    "Jen krátce: u sprchy sedí a slouží.",
    "Bez dramat — u sprchy funguje.",
    "Klidná objednávka, výsledek u sprchy sedí.",
    "Na čekání u sprchy jsme byli trpěliví, výsledek sedí.",
    "První dojem z krabice u sprchy byl v pohodě.",
    "Neošidili jsme výběr u sprchy.",
    "Nepůsobí jako showroom kus u sprchy.",
    "Do staršího interiéru u sprchy sedí líp než efekt.",
    "Funguje denně u sprchy bez řečí.",
    "Návštěvě u sprchy nemusím vysvětlovat.",
    "Prostě u sprchy to tam je a slouží.",
    "Otisky u sprchy utíráme, jinak klid.",
    "Denně u sprchy nepřemýšlíme.",
    "Do stejného řešení u sprchy bychom šli znovu.",
    "Údržba u sprchy nás nepřekvapila.",
    "Zapadlo to u sprchy bez dalšího řečení.",
    "Vypadá to u sprchy, jako by to tam bylo dřív.",
    "Schválně jsem hledal drobnosti u sprchy a moc jich nebylo.",
    "Až na otisky u sprchy bez výhrady.",
    "Montážní spáry u sprchy zůstaly čisté.",
    "Dělá svou práci u sprchy a nechce pozornost.",
    "Poměr cena a výsledek u sprchy nám sedí.",
    "Po usazení u sprchy jsme si oddychli.",
    "Dodatečně u sprchy jsme nemuseli nic doladit.",
    "V noci u sprchy nic necinká.",
    "Pro náš prostor u sprchy střízlivá volba.",
    "Po třech týdnech u sprchy stejný klid.",
    "Nic nepříjemně nepřekvapilo u sprchy.",
    "Pro naše rozměry u sprchy napoprvé.",
    "Tloušťku u sprchy bychom neměnili.",
    "Rozhodnutí jsme nespěchali a u sprchy to vyšlo.",
    "Po montáži u sprchy jsme nepotřebovali další zásah.",
    "Jsem rád, že jsme u sprchy nešli do zbytečného efektu.",
    "Celkově v pohodě u sprchy, bez velkých emocí.",
    "Uvidíme za rok; zatím u sprchy drží.",
    "Věcná spokojenost mi u sprchy stačí.",
    "Po prvním týdnu u sprchy už jen běžný provoz.",
    "Po předání u sprchy žádné volání navíc.",
    "Nemám chuť u sprchy cokoliv měnit.",
    "Běžný hadr stačí u sprchy.",
    "Nic mě nerozčiluje u sprchy při běžném používání.",
    "Po svátcích u sprchy pořád stejný dojem.",
    "Po prvním umytí u sprchy jako nové.",
    "Nepotřebuju to chválit nahlas — u sprchy sedí.",
    "Stačí mi, že u sprchy neřešíme.",
    "Dobrý kompromis bez marketingu u sprchy.",
    "V praxi u sprchy bez překvapení.",
    "Klidnější, než jsem u sprchy čekal.",
    "Po instalaci u sprchy žádné dodělávky.",
    "Vypadá střízlivě u sprchy, jak jsme chtěli.",
    "Spára u vaničky sedí, na dlažbu nezatéká.",
    "Sklo se po sprše rychle vytře do sucha.",
    "Voda zůstává uvnitř, dlažba sušší.",
    "Madlo je v pohodě i mokrýma rukama.",
    "Silikon u stěny drží, žádné fleky.",
    "Oproti fólii je to úplně jiná praxe.",
    "Po prvním týdnu přestalo páchnout silikonem.",
    "Těsnění u podlahy je rovné.",
    "Sklo nezkresluje barvu obkladu.",
    "Větrání koupelny sprchu nerozhodí.",
    "Dveře koutu se otvírají hladce.",
    "Po rekonstrukci to byl poslední díl koupelny.",
    "Až na vodní kámen nemám výhradu.",
    "Schválně jsem hledal netěsnost u vaničky a nenašel.",
    "Večer po montáži jsme se už sprchovali.",
]

ZABRADLI = [
    "U schodiště jsme objednali skleněné zábradlí.",
    "U schodiště jsme objednali výplň zábradlí.",
    "U schodiště jsme objednali zábradlí u galerie.",
    "U schodiště jsme objednali sklo na venkovní schody.",
    "U schodiště jsme objednali zábradlí k oknu.",
    "U schodiště jsme vybrali skleněné zábradlí.",
    "U schodiště jsme vybrali výplň zábradlí.",
    "U schodiště jsme vybrali zábradlí u galerie.",
    "U schodiště jsme vybrali sklo na venkovní schody.",
    "U schodiště jsme vybrali zábradlí k oknu.",
    "U schodiště jsme nechali udělat skleněné zábradlí.",
    "U schodiště jsme nechali udělat výplň zábradlí.",
    "U schodiště jsme nechali udělat zábradlí u galerie.",
    "U schodiště jsme nechali udělat sklo na venkovní schody.",
    "U schodiště jsme nechali udělat zábradlí k oknu.",
    "U schodiště jsme pořídili skleněné zábradlí.",
    "U schodiště jsme pořídili výplň zábradlí.",
    "U schodiště jsme pořídili zábradlí u galerie.",
    "U schodiště jsme pořídili sklo na venkovní schody.",
    "U schodiště jsme pořídili zábradlí k oknu.",
    "U schodiště jsme řešili skleněné zábradlí.",
    "U schodiště jsme řešili výplň zábradlí.",
    "U schodiště jsme řešili zábradlí u galerie.",
    "U schodiště jsme řešili sklo na venkovní schody.",
    "U schodiště jsme řešili zábradlí k oknu.",
    "U schodiště jsme doplnili skleněné zábradlí.",
    "U schodiště jsme doplnili výplň zábradlí.",
    "U schodiště jsme doplnili zábradlí u galerie.",
    "U schodiště jsme doplnili sklo na venkovní schody.",
    "U schodiště jsme doplnili zábradlí k oknu.",
    "U schodiště jsme vyměnili staré řešení za skleněné zábradlí.",
    "U schodiště jsme vyměnili staré řešení za výplň zábradlí.",
    "U schodiště jsme vyměnili staré řešení za zábradlí u galerie.",
    "U schodiště jsme vyměnili staré řešení za sklo na venkovní schody.",
    "U schodiště jsme vyměnili staré řešení za zábradlí k oknu.",
    "V novostavbě jsme objednali skleněné zábradlí.",
    "V novostavbě jsme objednali výplň zábradlí.",
    "V novostavbě jsme objednali zábradlí u galerie.",
    "V novostavbě jsme objednali sklo na venkovní schody.",
    "V novostavbě jsme objednali zábradlí k oknu.",
    "V novostavbě jsme vybrali skleněné zábradlí.",
    "V novostavbě jsme vybrali výplň zábradlí.",
    "V novostavbě jsme vybrali zábradlí u galerie.",
    "V novostavbě jsme vybrali sklo na venkovní schody.",
    "V novostavbě jsme vybrali zábradlí k oknu.",
    "V novostavbě jsme nechali udělat skleněné zábradlí.",
    "V novostavbě jsme nechali udělat výplň zábradlí.",
    "V novostavbě jsme nechali udělat zábradlí u galerie.",
    "V novostavbě jsme nechali udělat sklo na venkovní schody.",
    "V novostavbě jsme nechali udělat zábradlí k oknu.",
    "Chod je tichý u zábradlí.",
    "Údržba je jednoduchá u zábradlí.",
    "Hrany jsou hladké u zábradlí.",
    "Ukotvení je schované u zábradlí.",
    "Proporce sedí u zábradlí.",
    "Spára sedí u zábradlí.",
    "Nic nevibuje u zábradlí.",
    "Po měsíci stejný dojem u zábradlí.",
    "Bez servisu od montáže u zábradlí.",
    "Stačí běžný hadr u zábradlí.",
    "Montážníci uklidili u zábradlí.",
    "Termín napsali jasně u zábradlí.",
    "Komunikace byla stručná u zábradlí.",
    "Balení bylo poctivé u zábradlí.",
    "Dorazilo bez škrábnutí u zábradlí.",
    "Sedí napoprvé u zábradlí.",
    "Nepůsobí těžce u zábradlí.",
    "V provozu nenápadné u zábradlí.",
    "Zvykli jsme si rychle u zábradlí.",
    "Nemuseli jsme volat podruhé u zábradlí.",
    "Čas montáže dodrželi u zábradlí.",
    "Volali před příjezdem u zábradlí.",
    "Po týdnu bez výhrady u zábradlí.",
    "Za ty peníze dává smysl u zábradlí.",
    "Nic nestojí za řeč u zábradlí.",
    "Bereme to všedně u zábradlí.",
    "Výsledek sedí u zábradlí.",
    "Fotky seděly s realitou u zábradlí.",
    "Šlo to řešit na dálku u zábradlí.",
    "Nabídka byla srozumitelná u zábradlí.",
    "Rozhodnutí jsme nespěchali u zábradlí.",
    "Nešlo o efekt u zábradlí.",
    "Praktická volba u zábradlí.",
    "Po usazení klid u zábradlí.",
    "Druhý den jsme přestali kontrolovat u zábradlí.",
    "Návštěva nejdřív nic neřešila u zábradlí.",
    "Manželka je spokojená u zábradlí.",
    "Táta kontroloval úchyty u zábradlí.",
    "Architektka byla v pohodě u zábradlí.",
    "Po prvním umytí v pohodě u zábradlí.",
    "Stačí mi že to neřešíme u zábradlí.",
    "Věcná spokojenost stačí u zábradlí.",
    "Uvidíme za rok zatím drží u zábradlí.",
    "Celkově v pohodě u zábradlí.",
    "Žádné volání navíc u zábradlí.",
    "Liší se od starého řešení u zábradlí.",
    "Světlo zůstalo u zábradlí.",
    "Místo se neušetřilo zbytečně u zábradlí.",
    "Průvan to nerozhází u zábradlí.",
    "V zimě netáhne od spár u zábradlí.",
    "V létě to nepřehřívá dramaticky u zábradlí.",
    "Děti si zvykly u zábradlí.",
    "Pes to ignoruje u zábradlí.",
    "Soused poznamenal že je to čisté u zábradlí.",
    "Sourozenci se ptali stručně u zábradlí.",
    "Po svátcích stejný dojem u zábradlí.",
    "Mechanika drží u zábradlí.",
    "Šrouby se nepovolují u zábradlí.",
    "Vůle je v normě u zábradlí.",
    "Odstín kování sedí u zábradlí.",
    "Madlo sedí do ruky u zábradlí.",
    "Čistí se bez chemie u zábradlí.",
    "Prach utřeme rychle u zábradlí.",
    "Nepotřebuje zvláštní péči u zábradlí.",
    "Po půl roce stejný text u zábradlí.",
    "Kompromis nám sedí u zábradlí.",
    "Bez dodělávek u zábradlí.",
    "Bez reklamace u zábradlí.",
    "Bez show u zábradlí.",
    "Střízlivý výsledek u zábradlí.",
    "Po montáži u zábradlí jsme hned běžně používali prostor.",
    "Domluva u zábradlí šla přes mail bez zbytečných kol.",
    "Rozměr u zábradlí seděl napoprvé do připraveného otvoru.",
    "Přeprava u zábradlí proběhla bez dramatu.",
    "Na místě u zábradlí srovnali rychle dva lidé.",
    "Při vrtání u zábradlí zakryli okolí.",
    "Technik u zábradlí vysvětlil údržbu stručně.",
    "Po týdnu u zábradlí nemám co vytknout.",
    "Po měsíci u zábradlí pořád stejný klid.",
    "Po třech měsících u zábradlí nic povoleného.",
    "Za ty peníze u zábradlí férový výsledek.",
    "S výběrem u zábradlí jsme spokojení.",
    "Jen krátce: u zábradlí sedí a slouží.",
    "Bez dramat — u zábradlí funguje.",
    "Klidná objednávka, výsledek u zábradlí sedí.",
    "Na čekání u zábradlí jsme byli trpěliví, výsledek sedí.",
    "První dojem z krabice u zábradlí byl v pohodě.",
    "Neošidili jsme výběr u zábradlí.",
    "Nepůsobí jako showroom kus u zábradlí.",
    "Do staršího interiéru u zábradlí sedí líp než efekt.",
    "Funguje denně u zábradlí bez řečí.",
    "Návštěvě u zábradlí nemusím vysvětlovat.",
    "Prostě u zábradlí to tam je a slouží.",
    "Otisky u zábradlí utíráme, jinak klid.",
    "Denně u zábradlí nepřemýšlíme.",
    "Do stejného řešení u zábradlí bychom šli znovu.",
    "Údržba u zábradlí nás nepřekvapila.",
    "Zapadlo to u zábradlí bez dalšího řečení.",
    "Vypadá to u zábradlí, jako by to tam bylo dřív.",
    "Schválně jsem hledal drobnosti u zábradlí a moc jich nebylo.",
    "Až na otisky u zábradlí bez výhrady.",
    "Montážní spáry u zábradlí zůstaly čisté.",
    "Dělá svou práci u zábradlí a nechce pozornost.",
    "Poměr cena a výsledek u zábradlí nám sedí.",
    "Po usazení u zábradlí jsme si oddychli.",
    "Dodatečně u zábradlí jsme nemuseli nic doladit.",
    "V noci u zábradlí nic necinká.",
    "Pro náš prostor u zábradlí střízlivá volba.",
    "Po třech týdnech u zábradlí stejný klid.",
    "Nic nepříjemně nepřekvapilo u zábradlí.",
    "Pro naše rozměry u zábradlí napoprvé.",
    "Tloušťku u zábradlí bychom neměnili.",
    "Rozhodnutí jsme nespěchali a u zábradlí to vyšlo.",
    "Po montáži u zábradlí jsme nepotřebovali další zásah.",
    "Jsem rád, že jsme u zábradlí nešli do zbytečného efektu.",
    "Celkově v pohodě u zábradlí, bez velkých emocí.",
    "Uvidíme za rok; zatím u zábradlí drží.",
    "Věcná spokojenost mi u zábradlí stačí.",
    "Po prvním týdnu u zábradlí už jen běžný provoz.",
    "Po předání u zábradlí žádné volání navíc.",
    "Nemám chuť u zábradlí cokoliv měnit.",
    "Běžný hadr stačí u zábradlí.",
    "Nic mě nerozčiluje u zábradlí při běžném používání.",
    "Po svátcích u zábradlí pořád stejný dojem.",
    "Po prvním umytí u zábradlí jako nové.",
    "Nepotřebuju to chválit nahlas — u zábradlí sedí.",
    "Stačí mi, že u zábradlí neřešíme.",
    "Dobrý kompromis bez marketingu u zábradlí.",
    "V praxi u zábradlí bez překvapení.",
    "Klidnější, než jsem u zábradlí čekal.",
    "Po instalaci u zábradlí žádné dodělávky.",
    "Vypadá střízlivě u zábradlí, jak jsme chtěli.",
    "Galerie zůstala vzdušná.",
    "Madlo je příjemné do ruky při chůzi nahoru.",
    "Výhled do haly zůstal otevřený.",
    "Děti nemají kudy prolézt mezi stupni.",
    "Venkovní schody jsou po dešti bezpečnější na omak.",
    "U okna ubylo pocitu propasti.",
    "Šrouby jsou zarovnané, nic netrčí do průchodu.",
    "Schodiště působí otevřeněji než dřív.",
    "Na schodech je větší jistota s nákupem v ruce.",
    "Držení je jistější než u starého madla.",
    "Před výrobou ověřili výšku madla.",
    "Pes se o sklo otírá a nic se neděje.",
]

STRISKY = [
    "Nad vstupem jsme objednali skleněnou stříšku.",
    "Nad vstupem jsme objednali stříšku nad dveře.",
    "Nad vstupem jsme objednali přístřešek u vchodu.",
    "Nad vstupem jsme objednali stříšku na terasu.",
    "Nad vstupem jsme vybrali skleněnou stříšku.",
    "Nad vstupem jsme vybrali stříšku nad dveře.",
    "Nad vstupem jsme vybrali přístřešek u vchodu.",
    "Nad vstupem jsme vybrali stříšku na terasu.",
    "Nad vstupem jsme nechali udělat skleněnou stříšku.",
    "Nad vstupem jsme nechali udělat stříšku nad dveře.",
    "Nad vstupem jsme nechali udělat přístřešek u vchodu.",
    "Nad vstupem jsme nechali udělat stříšku na terasu.",
    "Nad vstupem jsme pořídili skleněnou stříšku.",
    "Nad vstupem jsme pořídili stříšku nad dveře.",
    "Nad vstupem jsme pořídili přístřešek u vchodu.",
    "Nad vstupem jsme pořídili stříšku na terasu.",
    "Nad vstupem jsme řešili skleněnou stříšku.",
    "Nad vstupem jsme řešili stříšku nad dveře.",
    "Nad vstupem jsme řešili přístřešek u vchodu.",
    "Nad vstupem jsme řešili stříšku na terasu.",
    "Nad vstupem jsme doplnili skleněnou stříšku.",
    "Nad vstupem jsme doplnili stříšku nad dveře.",
    "Nad vstupem jsme doplnili přístřešek u vchodu.",
    "Nad vstupem jsme doplnili stříšku na terasu.",
    "Nad vstupem jsme vyměnili staré řešení za skleněnou stříšku.",
    "Nad vstupem jsme vyměnili staré řešení za stříšku nad dveře.",
    "Nad vstupem jsme vyměnili staré řešení za přístřešek u vchodu.",
    "Nad vstupem jsme vyměnili staré řešení za stříšku na terasu.",
    "U zadního vchodu jsme objednali skleněnou stříšku.",
    "U zadního vchodu jsme objednali stříšku nad dveře.",
    "U zadního vchodu jsme objednali přístřešek u vchodu.",
    "U zadního vchodu jsme objednali stříšku na terasu.",
    "U zadního vchodu jsme vybrali skleněnou stříšku.",
    "U zadního vchodu jsme vybrali stříšku nad dveře.",
    "U zadního vchodu jsme vybrali přístřešek u vchodu.",
    "U zadního vchodu jsme vybrali stříšku na terasu.",
    "U zadního vchodu jsme nechali udělat skleněnou stříšku.",
    "U zadního vchodu jsme nechali udělat stříšku nad dveře.",
    "U zadního vchodu jsme nechali udělat přístřešek u vchodu.",
    "U zadního vchodu jsme nechali udělat stříšku na terasu.",
    "U zadního vchodu jsme pořídili skleněnou stříšku.",
    "U zadního vchodu jsme pořídili stříšku nad dveře.",
    "U zadního vchodu jsme pořídili přístřešek u vchodu.",
    "U zadního vchodu jsme pořídili stříšku na terasu.",
    "U zadního vchodu jsme řešili skleněnou stříšku.",
    "U zadního vchodu jsme řešili stříšku nad dveře.",
    "U zadního vchodu jsme řešili přístřešek u vchodu.",
    "U zadního vchodu jsme řešili stříšku na terasu.",
    "U zadního vchodu jsme doplnili skleněnou stříšku.",
    "U zadního vchodu jsme doplnili stříšku nad dveře.",
    "Chod je tichý u stříšky.",
    "Údržba je jednoduchá u stříšky.",
    "Hrany jsou hladké u stříšky.",
    "Ukotvení je schované u stříšky.",
    "Proporce sedí u stříšky.",
    "Spára sedí u stříšky.",
    "Nic nevibuje u stříšky.",
    "Po měsíci stejný dojem u stříšky.",
    "Bez servisu od montáže u stříšky.",
    "Stačí běžný hadr u stříšky.",
    "Montážníci uklidili u stříšky.",
    "Termín napsali jasně u stříšky.",
    "Komunikace byla stručná u stříšky.",
    "Balení bylo poctivé u stříšky.",
    "Dorazilo bez škrábnutí u stříšky.",
    "Sedí napoprvé u stříšky.",
    "Nepůsobí těžce u stříšky.",
    "V provozu nenápadné u stříšky.",
    "Zvykli jsme si rychle u stříšky.",
    "Nemuseli jsme volat podruhé u stříšky.",
    "Čas montáže dodrželi u stříšky.",
    "Volali před příjezdem u stříšky.",
    "Po týdnu bez výhrady u stříšky.",
    "Za ty peníze dává smysl u stříšky.",
    "Nic nestojí za řeč u stříšky.",
    "Bereme to všedně u stříšky.",
    "Výsledek sedí u stříšky.",
    "Fotky seděly s realitou u stříšky.",
    "Šlo to řešit na dálku u stříšky.",
    "Nabídka byla srozumitelná u stříšky.",
    "Rozhodnutí jsme nespěchali u stříšky.",
    "Nešlo o efekt u stříšky.",
    "Praktická volba u stříšky.",
    "Po usazení klid u stříšky.",
    "Druhý den jsme přestali kontrolovat u stříšky.",
    "Návštěva nejdřív nic neřešila u stříšky.",
    "Manželka je spokojená u stříšky.",
    "Táta kontroloval úchyty u stříšky.",
    "Architektka byla v pohodě u stříšky.",
    "Po prvním umytí v pohodě u stříšky.",
    "Stačí mi že to neřešíme u stříšky.",
    "Věcná spokojenost stačí u stříšky.",
    "Uvidíme za rok zatím drží u stříšky.",
    "Celkově v pohodě u stříšky.",
    "Žádné volání navíc u stříšky.",
    "Liší se od starého řešení u stříšky.",
    "Světlo zůstalo u stříšky.",
    "Místo se neušetřilo zbytečně u stříšky.",
    "Průvan to nerozhází u stříšky.",
    "V zimě netáhne od spár u stříšky.",
    "V létě to nepřehřívá dramaticky u stříšky.",
    "Děti si zvykly u stříšky.",
    "Pes to ignoruje u stříšky.",
    "Soused poznamenal že je to čisté u stříšky.",
    "Sourozenci se ptali stručně u stříšky.",
    "Po svátcích stejný dojem u stříšky.",
    "Mechanika drží u stříšky.",
    "Šrouby se nepovolují u stříšky.",
    "Vůle je v normě u stříšky.",
    "Odstín kování sedí u stříšky.",
    "Madlo sedí do ruky u stříšky.",
    "Čistí se bez chemie u stříšky.",
    "Prach utřeme rychle u stříšky.",
    "Nepotřebuje zvláštní péči u stříšky.",
    "Po půl roce stejný text u stříšky.",
    "Kompromis nám sedí u stříšky.",
    "Bez dodělávek u stříšky.",
    "Bez reklamace u stříšky.",
    "Bez show u stříšky.",
    "Střízlivý výsledek u stříšky.",
    "Po montáži u stříšky jsme hned běžně používali prostor.",
    "Domluva u stříšky šla přes mail bez zbytečných kol.",
    "Rozměr u stříšky seděl napoprvé do připraveného otvoru.",
    "Přeprava u stříšky proběhla bez dramatu.",
    "Na místě u stříšky srovnali rychle dva lidé.",
    "Při vrtání u stříšky zakryli okolí.",
    "Technik u stříšky vysvětlil údržbu stručně.",
    "Po týdnu u stříšky nemám co vytknout.",
    "Po měsíci u stříšky pořád stejný klid.",
    "Po třech měsících u stříšky nic povoleného.",
    "Za ty peníze u stříšky férový výsledek.",
    "S výběrem u stříšky jsme spokojení.",
    "Jen krátce: u stříšky sedí a slouží.",
    "Bez dramat — u stříšky funguje.",
    "Klidná objednávka, výsledek u stříšky sedí.",
    "Na čekání u stříšky jsme byli trpěliví, výsledek sedí.",
    "První dojem z krabice u stříšky byl v pohodě.",
    "Neošidili jsme výběr u stříšky.",
    "Nepůsobí jako showroom kus u stříšky.",
    "Do staršího interiéru u stříšky sedí líp než efekt.",
    "Funguje denně u stříšky bez řečí.",
    "Návštěvě u stříšky nemusím vysvětlovat.",
    "Prostě u stříšky to tam je a slouží.",
    "Otisky u stříšky utíráme, jinak klid.",
    "Denně u stříšky nepřemýšlíme.",
    "Do stejného řešení u stříšky bychom šli znovu.",
    "Údržba u stříšky nás nepřekvapila.",
    "Zapadlo to u stříšky bez dalšího řečení.",
    "Vypadá to u stříšky, jako by to tam bylo dřív.",
    "Schválně jsem hledal drobnosti u stříšky a moc jich nebylo.",
    "Až na otisky u stříšky bez výhrady.",
    "Montážní spáry u stříšky zůstaly čisté.",
    "Dělá svou práci u stříšky a nechce pozornost.",
    "Poměr cena a výsledek u stříšky nám sedí.",
    "Po usazení u stříšky jsme si oddychli.",
    "Dodatečně u stříšky jsme nemuseli nic doladit.",
    "V noci u stříšky nic necinká.",
    "Pro náš prostor u stříšky střízlivá volba.",
    "Po třech týdnech u stříšky stejný klid.",
    "Nic nepříjemně nepřekvapilo u stříšky.",
    "Pro naše rozměry u stříšky napoprvé.",
    "Tloušťku u stříšky bychom neměnili.",
    "Rozhodnutí jsme nespěchali a u stříšky to vyšlo.",
    "Po montáži u stříšky jsme nepotřebovali další zásah.",
    "Jsem rád, že jsme u stříšky nešli do zbytečného efektu.",
    "Celkově v pohodě u stříšky, bez velkých emocí.",
    "Uvidíme za rok; zatím u stříšky drží.",
    "Věcná spokojenost mi u stříšky stačí.",
    "Po prvním týdnu u stříšky už jen běžný provoz.",
    "Po předání u stříšky žádné volání navíc.",
    "Nemám chuť u stříšky cokoliv měnit.",
    "Běžný hadr stačí u stříšky.",
    "Nic mě nerozčiluje u stříšky při běžném používání.",
    "Po svátcích u stříšky pořád stejný dojem.",
    "Po prvním umytí u stříšky jako nové.",
    "Nepotřebuju to chválit nahlas — u stříšky sedí.",
    "Stačí mi, že u stříšky neřešíme.",
    "Dobrý kompromis bez marketingu u stříšky.",
    "V praxi u stříšky bez překvapení.",
    "Klidnější, než jsem u stříšky čekal.",
    "Po instalaci u stříšky žádné dodělávky.",
    "Vypadá střízlivě u stříšky, jak jsme chtěli.",
    "Po dešti sušší boty u prahu.",
    "Sklon odvádí vodu pryč od zárubně.",
    "Větrné dny zvládá bez rachotu.",
    "V létě stíní práh jen lehce.",
    "Kotvení do zdi je čisté.",
    "Schválně jsem hledal odkap a je správně směřovaný.",
    "V zimě oceníme suchý práh pod stříškou.",
    "Odvede vodu mimo práh u vstupních dveří.",
]

PRICKY = [
    "Mezi kuchyní a obývákem jsme objednali skleněnou příčku.",
    "Mezi kuchyní a obývákem jsme objednali příčku do pracovny.",
    "Mezi kuchyní a obývákem jsme objednali dělicí stěnu.",
    "Mezi kuchyní a obývákem jsme objednali příčku do chodby.",
    "Mezi kuchyní a obývákem jsme vybrali skleněnou příčku.",
    "Mezi kuchyní a obývákem jsme vybrali příčku do pracovny.",
    "Mezi kuchyní a obývákem jsme vybrali dělicí stěnu.",
    "Mezi kuchyní a obývákem jsme vybrali příčku do chodby.",
    "Mezi kuchyní a obývákem jsme nechali udělat skleněnou příčku.",
    "Mezi kuchyní a obývákem jsme nechali udělat příčku do pracovny.",
    "Mezi kuchyní a obývákem jsme nechali udělat dělicí stěnu.",
    "Mezi kuchyní a obývákem jsme nechali udělat příčku do chodby.",
    "Mezi kuchyní a obývákem jsme pořídili skleněnou příčku.",
    "Mezi kuchyní a obývákem jsme pořídili příčku do pracovny.",
    "Mezi kuchyní a obývákem jsme pořídili dělicí stěnu.",
    "Mezi kuchyní a obývákem jsme pořídili příčku do chodby.",
    "Mezi kuchyní a obývákem jsme řešili skleněnou příčku.",
    "Mezi kuchyní a obývákem jsme řešili příčku do pracovny.",
    "Mezi kuchyní a obývákem jsme řešili dělicí stěnu.",
    "Mezi kuchyní a obývákem jsme řešili příčku do chodby.",
    "Mezi kuchyní a obývákem jsme doplnili skleněnou příčku.",
    "Mezi kuchyní a obývákem jsme doplnili příčku do pracovny.",
    "Mezi kuchyní a obývákem jsme doplnili dělicí stěnu.",
    "Mezi kuchyní a obývákem jsme doplnili příčku do chodby.",
    "Mezi kuchyní a obývákem jsme vyměnili staré řešení za skleněnou příčku.",
    "Mezi kuchyní a obývákem jsme vyměnili staré řešení za příčku do pracovny.",
    "Mezi kuchyní a obývákem jsme vyměnili staré řešení za dělicí stěnu.",
    "Mezi kuchyní a obývákem jsme vyměnili staré řešení za příčku do chodby.",
    "V pracovně doma jsme objednali skleněnou příčku.",
    "V pracovně doma jsme objednali příčku do pracovny.",
    "V pracovně doma jsme objednali dělicí stěnu.",
    "V pracovně doma jsme objednali příčku do chodby.",
    "V pracovně doma jsme vybrali skleněnou příčku.",
    "V pracovně doma jsme vybrali příčku do pracovny.",
    "V pracovně doma jsme vybrali dělicí stěnu.",
    "V pracovně doma jsme vybrali příčku do chodby.",
    "V pracovně doma jsme nechali udělat skleněnou příčku.",
    "V pracovně doma jsme nechali udělat příčku do pracovny.",
    "V pracovně doma jsme nechali udělat dělicí stěnu.",
    "V pracovně doma jsme nechali udělat příčku do chodby.",
    "V pracovně doma jsme pořídili skleněnou příčku.",
    "V pracovně doma jsme pořídili příčku do pracovny.",
    "V pracovně doma jsme pořídili dělicí stěnu.",
    "V pracovně doma jsme pořídili příčku do chodby.",
    "V pracovně doma jsme řešili skleněnou příčku.",
    "V pracovně doma jsme řešili příčku do pracovny.",
    "V pracovně doma jsme řešili dělicí stěnu.",
    "V pracovně doma jsme řešili příčku do chodby.",
    "V pracovně doma jsme doplnili skleněnou příčku.",
    "V pracovně doma jsme doplnili příčku do pracovny.",
    "Chod je tichý u příčky.",
    "Údržba je jednoduchá u příčky.",
    "Hrany jsou hladké u příčky.",
    "Ukotvení je schované u příčky.",
    "Proporce sedí u příčky.",
    "Spára sedí u příčky.",
    "Nic nevibuje u příčky.",
    "Po měsíci stejný dojem u příčky.",
    "Bez servisu od montáže u příčky.",
    "Stačí běžný hadr u příčky.",
    "Montážníci uklidili u příčky.",
    "Termín napsali jasně u příčky.",
    "Komunikace byla stručná u příčky.",
    "Balení bylo poctivé u příčky.",
    "Dorazilo bez škrábnutí u příčky.",
    "Sedí napoprvé u příčky.",
    "Nepůsobí těžce u příčky.",
    "V provozu nenápadné u příčky.",
    "Zvykli jsme si rychle u příčky.",
    "Nemuseli jsme volat podruhé u příčky.",
    "Čas montáže dodrželi u příčky.",
    "Volali před příjezdem u příčky.",
    "Po týdnu bez výhrady u příčky.",
    "Za ty peníze dává smysl u příčky.",
    "Nic nestojí za řeč u příčky.",
    "Bereme to všedně u příčky.",
    "Výsledek sedí u příčky.",
    "Fotky seděly s realitou u příčky.",
    "Šlo to řešit na dálku u příčky.",
    "Nabídka byla srozumitelná u příčky.",
    "Rozhodnutí jsme nespěchali u příčky.",
    "Nešlo o efekt u příčky.",
    "Praktická volba u příčky.",
    "Po usazení klid u příčky.",
    "Druhý den jsme přestali kontrolovat u příčky.",
    "Návštěva nejdřív nic neřešila u příčky.",
    "Manželka je spokojená u příčky.",
    "Táta kontroloval úchyty u příčky.",
    "Architektka byla v pohodě u příčky.",
    "Po prvním umytí v pohodě u příčky.",
    "Stačí mi že to neřešíme u příčky.",
    "Věcná spokojenost stačí u příčky.",
    "Uvidíme za rok zatím drží u příčky.",
    "Celkově v pohodě u příčky.",
    "Žádné volání navíc u příčky.",
    "Liší se od starého řešení u příčky.",
    "Světlo zůstalo u příčky.",
    "Místo se neušetřilo zbytečně u příčky.",
    "Průvan to nerozhází u příčky.",
    "V zimě netáhne od spár u příčky.",
    "V létě to nepřehřívá dramaticky u příčky.",
    "Děti si zvykly u příčky.",
    "Pes to ignoruje u příčky.",
    "Soused poznamenal že je to čisté u příčky.",
    "Sourozenci se ptali stručně u příčky.",
    "Po svátcích stejný dojem u příčky.",
    "Mechanika drží u příčky.",
    "Šrouby se nepovolují u příčky.",
    "Vůle je v normě u příčky.",
    "Odstín kování sedí u příčky.",
    "Madlo sedí do ruky u příčky.",
    "Čistí se bez chemie u příčky.",
    "Prach utřeme rychle u příčky.",
    "Nepotřebuje zvláštní péči u příčky.",
    "Po půl roce stejný text u příčky.",
    "Kompromis nám sedí u příčky.",
    "Bez dodělávek u příčky.",
    "Bez reklamace u příčky.",
    "Bez show u příčky.",
    "Střízlivý výsledek u příčky.",
    "Po montáži u příčky jsme hned běžně používali prostor.",
    "Domluva u příčky šla přes mail bez zbytečných kol.",
    "Rozměr u příčky seděl napoprvé do připraveného otvoru.",
    "Přeprava u příčky proběhla bez dramatu.",
    "Na místě u příčky srovnali rychle dva lidé.",
    "Při vrtání u příčky zakryli okolí.",
    "Technik u příčky vysvětlil údržbu stručně.",
    "Po týdnu u příčky nemám co vytknout.",
    "Po měsíci u příčky pořád stejný klid.",
    "Po třech měsících u příčky nic povoleného.",
    "Za ty peníze u příčky férový výsledek.",
    "S výběrem u příčky jsme spokojení.",
    "Jen krátce: u příčky sedí a slouží.",
    "Bez dramat — u příčky funguje.",
    "Klidná objednávka, výsledek u příčky sedí.",
    "Na čekání u příčky jsme byli trpěliví, výsledek sedí.",
    "První dojem z krabice u příčky byl v pohodě.",
    "Neošidili jsme výběr u příčky.",
    "Nepůsobí jako showroom kus u příčky.",
    "Do staršího interiéru u příčky sedí líp než efekt.",
    "Funguje denně u příčky bez řečí.",
    "Návštěvě u příčky nemusím vysvětlovat.",
    "Prostě u příčky to tam je a slouží.",
    "Otisky u příčky utíráme, jinak klid.",
    "Denně u příčky nepřemýšlíme.",
    "Do stejného řešení u příčky bychom šli znovu.",
    "Údržba u příčky nás nepřekvapila.",
    "Zapadlo to u příčky bez dalšího řečení.",
    "Vypadá to u příčky, jako by to tam bylo dřív.",
    "Schválně jsem hledal drobnosti u příčky a moc jich nebylo.",
    "Až na otisky u příčky bez výhrady.",
    "Montážní spáry u příčky zůstaly čisté.",
    "Dělá svou práci u příčky a nechce pozornost.",
    "Poměr cena a výsledek u příčky nám sedí.",
    "Po usazení u příčky jsme si oddychli.",
    "Dodatečně u příčky jsme nemuseli nic doladit.",
    "V noci u příčky nic necinká.",
    "Pro náš prostor u příčky střízlivá volba.",
    "Po třech týdnech u příčky stejný klid.",
    "Nic nepříjemně nepřekvapilo u příčky.",
    "Pro naše rozměry u příčky napoprvé.",
    "Tloušťku u příčky bychom neměnili.",
    "Rozhodnutí jsme nespěchali a u příčky to vyšlo.",
    "Po montáži u příčky jsme nepotřebovali další zásah.",
    "Jsem rád, že jsme u příčky nešli do zbytečného efektu.",
    "Celkově v pohodě u příčky, bez velkých emocí.",
    "Uvidíme za rok; zatím u příčky drží.",
    "Věcná spokojenost mi u příčky stačí.",
    "Po prvním týdnu u příčky už jen běžný provoz.",
    "Po předání u příčky žádné volání navíc.",
    "Nemám chuť u příčky cokoliv měnit.",
    "Běžný hadr stačí u příčky.",
    "Nic mě nerozčiluje u příčky při běžném používání.",
    "Po svátcích u příčky pořád stejný dojem.",
    "Po prvním umytí u příčky jako nové.",
    "Nepotřebuju to chválit nahlas — u příčky sedí.",
    "Stačí mi, že u příčky neřešíme.",
    "Dobrý kompromis bez marketingu u příčky.",
    "V praxi u příčky bez překvapení.",
    "Klidnější, než jsem u příčky čekal.",
    "Po instalaci u příčky žádné dodělávky.",
    "Vypadá střízlivě u příčky, jak jsme chtěli.",
    "Hovory z callu už neruší obývák tolik.",
    "Pára z vaření zůstává spíš v kuchyni.",
    "Kočka sklo příčky ignoruje, což je úspěch.",
    "Večer při televizi je míň hluku z digestoře.",
    "Ráno je pracovna oddělená bez tmy.",
    "Příčka změnila hlavně akustiku, ne světlo.",
    "Hluk z kuchyně je po příčce mírnější.",
    "Plocha příčky není zelená, odstín je v pohodě.",
]

BALKONY = [
    "Na balkoně jsme objednali sklo na balkon.",
    "Na balkoně jsme objednali balkonovou výplň.",
    "Na balkoně jsme objednali zasklení lodžie.",
    "Na balkoně jsme objednali skleněnou výplň terasy.",
    "Na balkoně jsme vybrali sklo na balkon.",
    "Na balkoně jsme vybrali balkonovou výplň.",
    "Na balkoně jsme vybrali zasklení lodžie.",
    "Na balkoně jsme vybrali skleněnou výplň terasy.",
    "Na balkoně jsme nechali udělat sklo na balkon.",
    "Na balkoně jsme nechali udělat balkonovou výplň.",
    "Na balkoně jsme nechali udělat zasklení lodžie.",
    "Na balkoně jsme nechali udělat skleněnou výplň terasy.",
    "Na balkoně jsme pořídili sklo na balkon.",
    "Na balkoně jsme pořídili balkonovou výplň.",
    "Na balkoně jsme pořídili zasklení lodžie.",
    "Na balkoně jsme pořídili skleněnou výplň terasy.",
    "Na balkoně jsme řešili sklo na balkon.",
    "Na balkoně jsme řešili balkonovou výplň.",
    "Na balkoně jsme řešili zasklení lodžie.",
    "Na balkoně jsme řešili skleněnou výplň terasy.",
    "Na balkoně jsme doplnili sklo na balkon.",
    "Na balkoně jsme doplnili balkonovou výplň.",
    "Na balkoně jsme doplnili zasklení lodžie.",
    "Na balkoně jsme doplnili skleněnou výplň terasy.",
    "Na balkoně jsme vyměnili staré řešení za sklo na balkon.",
    "Na balkoně jsme vyměnili staré řešení za balkonovou výplň.",
    "Na balkoně jsme vyměnili staré řešení za zasklení lodžie.",
    "Na balkoně jsme vyměnili staré řešení za skleněnou výplň terasy.",
    "V lodžii jsme objednali sklo na balkon.",
    "V lodžii jsme objednali balkonovou výplň.",
    "V lodžii jsme objednali zasklení lodžie.",
    "V lodžii jsme objednali skleněnou výplň terasy.",
    "V lodžii jsme vybrali sklo na balkon.",
    "V lodžii jsme vybrali balkonovou výplň.",
    "V lodžii jsme vybrali zasklení lodžie.",
    "V lodžii jsme vybrali skleněnou výplň terasy.",
    "V lodžii jsme nechali udělat sklo na balkon.",
    "V lodžii jsme nechali udělat balkonovou výplň.",
    "V lodžii jsme nechali udělat zasklení lodžie.",
    "V lodžii jsme nechali udělat skleněnou výplň terasy.",
    "V lodžii jsme pořídili sklo na balkon.",
    "V lodžii jsme pořídili balkonovou výplň.",
    "V lodžii jsme pořídili zasklení lodžie.",
    "V lodžii jsme pořídili skleněnou výplň terasy.",
    "V lodžii jsme řešili sklo na balkon.",
    "V lodžii jsme řešili balkonovou výplň.",
    "V lodžii jsme řešili zasklení lodžie.",
    "V lodžii jsme řešili skleněnou výplň terasy.",
    "V lodžii jsme doplnili sklo na balkon.",
    "V lodžii jsme doplnili balkonovou výplň.",
    "Chod je tichý na balkoně.",
    "Údržba je jednoduchá na balkoně.",
    "Hrany jsou hladké na balkoně.",
    "Ukotvení je schované na balkoně.",
    "Proporce sedí na balkoně.",
    "Spára sedí na balkoně.",
    "Nic nevibuje na balkoně.",
    "Po měsíci stejný dojem na balkoně.",
    "Bez servisu od montáže na balkoně.",
    "Stačí běžný hadr na balkoně.",
    "Montážníci uklidili na balkoně.",
    "Termín napsali jasně na balkoně.",
    "Komunikace byla stručná na balkoně.",
    "Balení bylo poctivé na balkoně.",
    "Dorazilo bez škrábnutí na balkoně.",
    "Sedí napoprvé na balkoně.",
    "Nepůsobí těžce na balkoně.",
    "V provozu nenápadné na balkoně.",
    "Zvykli jsme si rychle na balkoně.",
    "Nemuseli jsme volat podruhé na balkoně.",
    "Čas montáže dodrželi na balkoně.",
    "Volali před příjezdem na balkoně.",
    "Po týdnu bez výhrady na balkoně.",
    "Za ty peníze dává smysl na balkoně.",
    "Nic nestojí za řeč na balkoně.",
    "Bereme to všedně na balkoně.",
    "Výsledek sedí na balkoně.",
    "Fotky seděly s realitou na balkoně.",
    "Šlo to řešit na dálku na balkoně.",
    "Nabídka byla srozumitelná na balkoně.",
    "Rozhodnutí jsme nespěchali na balkoně.",
    "Nešlo o efekt na balkoně.",
    "Praktická volba na balkoně.",
    "Po usazení klid na balkoně.",
    "Druhý den jsme přestali kontrolovat na balkoně.",
    "Návštěva nejdřív nic neřešila na balkoně.",
    "Manželka je spokojená na balkoně.",
    "Táta kontroloval úchyty na balkoně.",
    "Architektka byla v pohodě na balkoně.",
    "Po prvním umytí v pohodě na balkoně.",
    "Stačí mi že to neřešíme na balkoně.",
    "Věcná spokojenost stačí na balkoně.",
    "Uvidíme za rok zatím drží na balkoně.",
    "Celkově v pohodě na balkoně.",
    "Žádné volání navíc na balkoně.",
    "Liší se od starého řešení na balkoně.",
    "Světlo zůstalo na balkoně.",
    "Místo se neušetřilo zbytečně na balkoně.",
    "Průvan to nerozhází na balkoně.",
    "V zimě netáhne od spár na balkoně.",
    "V létě to nepřehřívá dramaticky na balkoně.",
    "Děti si zvykly na balkoně.",
    "Pes to ignoruje na balkoně.",
    "Soused poznamenal že je to čisté na balkoně.",
    "Sourozenci se ptali stručně na balkoně.",
    "Po svátcích stejný dojem na balkoně.",
    "Mechanika drží na balkoně.",
    "Šrouby se nepovolují na balkoně.",
    "Vůle je v normě na balkoně.",
    "Odstín kování sedí na balkoně.",
    "Madlo sedí do ruky na balkoně.",
    "Čistí se bez chemie na balkoně.",
    "Prach utřeme rychle na balkoně.",
    "Nepotřebuje zvláštní péči na balkoně.",
    "Po půl roce stejný text na balkoně.",
    "Kompromis nám sedí na balkoně.",
    "Bez dodělávek na balkoně.",
    "Bez reklamace na balkoně.",
    "Bez show na balkoně.",
    "Střízlivý výsledek na balkoně.",
    "Po montáži na balkoně jsme hned běžně používali prostor.",
    "Domluva na balkoně šla přes mail bez zbytečných kol.",
    "Rozměr na balkoně seděl napoprvé do připraveného otvoru.",
    "Přeprava na balkoně proběhla bez dramatu.",
    "Na místě na balkoně srovnali rychle dva lidé.",
    "Při vrtání na balkoně zakryli okolí.",
    "Technik na balkoně vysvětlil údržbu stručně.",
    "Po týdnu na balkoně nemám co vytknout.",
    "Po měsíci na balkoně pořád stejný klid.",
    "Po třech měsících na balkoně nic povoleného.",
    "Za ty peníze na balkoně férový výsledek.",
    "S výběrem na balkoně jsme spokojení.",
    "Jen krátce: na balkoně sedí a slouží.",
    "Bez dramat — na balkoně funguje.",
    "Klidná objednávka, výsledek na balkoně sedí.",
    "Na čekání na balkoně jsme byli trpěliví, výsledek sedí.",
    "První dojem z krabice na balkoně byl v pohodě.",
    "Neošidili jsme výběr na balkoně.",
    "Nepůsobí jako showroom kus na balkoně.",
    "Do staršího interiéru na balkoně sedí líp než efekt.",
    "Funguje denně na balkoně bez řečí.",
    "Návštěvě na balkoně nemusím vysvětlovat.",
    "Prostě na balkoně to tam je a slouží.",
    "Otisky na balkoně utíráme, jinak klid.",
    "Denně na balkoně nepřemýšlíme.",
    "Do stejného řešení na balkoně bychom šli znovu.",
    "Údržba na balkoně nás nepřekvapila.",
    "Zapadlo to na balkoně bez dalšího řečení.",
    "Vypadá to na balkoně, jako by to tam bylo dřív.",
    "Schválně jsem hledal drobnosti na balkoně a moc jich nebylo.",
    "Až na otisky na balkoně bez výhrady.",
    "Montážní spáry na balkoně zůstaly čisté.",
    "Dělá svou práci na balkoně a nechce pozornost.",
    "Poměr cena a výsledek na balkoně nám sedí.",
    "Po usazení na balkoně jsme si oddychli.",
    "Dodatečně na balkoně jsme nemuseli nic doladit.",
    "V noci na balkoně nic necinká.",
    "Pro náš prostor na balkoně střízlivá volba.",
    "Po třech týdnech na balkoně stejný klid.",
    "Nic nepříjemně nepřekvapilo na balkoně.",
    "Pro naše rozměry na balkoně napoprvé.",
    "Tloušťku na balkoně bychom neměnili.",
    "Rozhodnutí jsme nespěchali a na balkoně to vyšlo.",
    "Po montáži na balkoně jsme nepotřebovali další zásah.",
    "Jsem rád, že jsme na balkoně nešli do zbytečného efektu.",
    "Celkově v pohodě na balkoně, bez velkých emocí.",
    "Uvidíme za rok; zatím na balkoně drží.",
    "Věcná spokojenost mi na balkoně stačí.",
    "Po prvním týdnu na balkoně už jen běžný provoz.",
    "Po předání na balkoně žádné volání navíc.",
    "Nemám chuť na balkoně cokoliv měnit.",
    "Běžný hadr stačí na balkoně.",
    "Nic mě nerozčiluje na balkoně při běžném používání.",
    "Po svátcích na balkoně pořád stejný dojem.",
    "Po prvním umytí na balkoně jako nové.",
    "Nepotřebuju to chválit nahlas — na balkoně sedí.",
    "Stačí mi, že na balkoně neřešíme.",
    "Dobrý kompromis bez marketingu na balkoně.",
    "V praxi na balkoně bez překvapení.",
    "Klidnější, než jsem na balkoně čekal.",
    "Po instalaci na balkoně žádné dodělávky.",
    "Vypadá střízlivě na balkoně, jak jsme chtěli.",
    "Ráno u kafe je míň větru.",
    "Sušení prádla jde i za větrnějších dnů.",
    "Prachu z ulice na balkoně ubylo.",
    "V dešti zůstane židle suchá u zdi.",
    "Zasklení změnilo hlavně použitelnost lodžie.",
    "V lodžii jde sedět i za deště.",
    "Na patře ubylo prachu z ulice.",
]

OSTATNI = [
    "Za kuchyňskou linkou jsme objednali zrcadlo na míru.",
    "Za kuchyňskou linkou jsme objednali sklo za linku.",
    "Za kuchyňskou linkou jsme objednali skleněnou polici.",
    "Za kuchyňskou linkou jsme objednali náhradní tabuli.",
    "Za kuchyňskou linkou jsme vybrali zrcadlo na míru.",
    "Za kuchyňskou linkou jsme vybrali sklo za linku.",
    "Za kuchyňskou linkou jsme vybrali skleněnou polici.",
    "Za kuchyňskou linkou jsme vybrali náhradní tabuli.",
    "Za kuchyňskou linkou jsme nechali udělat zrcadlo na míru.",
    "Za kuchyňskou linkou jsme nechali udělat sklo za linku.",
    "Za kuchyňskou linkou jsme nechali udělat skleněnou polici.",
    "Za kuchyňskou linkou jsme nechali udělat náhradní tabuli.",
    "Za kuchyňskou linkou jsme pořídili zrcadlo na míru.",
    "Za kuchyňskou linkou jsme pořídili sklo za linku.",
    "Za kuchyňskou linkou jsme pořídili skleněnou polici.",
    "Za kuchyňskou linkou jsme pořídili náhradní tabuli.",
    "Za kuchyňskou linkou jsme řešili zrcadlo na míru.",
    "Za kuchyňskou linkou jsme řešili sklo za linku.",
    "Za kuchyňskou linkou jsme řešili skleněnou polici.",
    "Za kuchyňskou linkou jsme řešili náhradní tabuli.",
    "Za kuchyňskou linkou jsme doplnili zrcadlo na míru.",
    "Za kuchyňskou linkou jsme doplnili sklo za linku.",
    "Za kuchyňskou linkou jsme doplnili skleněnou polici.",
    "Za kuchyňskou linkou jsme doplnili náhradní tabuli.",
    "Za kuchyňskou linkou jsme vyměnili staré řešení za zrcadlo na míru.",
    "Za kuchyňskou linkou jsme vyměnili staré řešení za sklo za linku.",
    "Za kuchyňskou linkou jsme vyměnili staré řešení za skleněnou polici.",
    "Za kuchyňskou linkou jsme vyměnili staré řešení za náhradní tabuli.",
    "Po rekonstrukci linky jsme objednali zrcadlo na míru.",
    "Po rekonstrukci linky jsme objednali sklo za linku.",
    "Po rekonstrukci linky jsme objednali skleněnou polici.",
    "Po rekonstrukci linky jsme objednali náhradní tabuli.",
    "Po rekonstrukci linky jsme vybrali zrcadlo na míru.",
    "Po rekonstrukci linky jsme vybrali sklo za linku.",
    "Po rekonstrukci linky jsme vybrali skleněnou polici.",
    "Po rekonstrukci linky jsme vybrali náhradní tabuli.",
    "Po rekonstrukci linky jsme nechali udělat zrcadlo na míru.",
    "Po rekonstrukci linky jsme nechali udělat sklo za linku.",
    "Po rekonstrukci linky jsme nechali udělat skleněnou polici.",
    "Po rekonstrukci linky jsme nechali udělat náhradní tabuli.",
    "Po rekonstrukci linky jsme pořídili zrcadlo na míru.",
    "Po rekonstrukci linky jsme pořídili sklo za linku.",
    "Po rekonstrukci linky jsme pořídili skleněnou polici.",
    "Po rekonstrukci linky jsme pořídili náhradní tabuli.",
    "Po rekonstrukci linky jsme řešili zrcadlo na míru.",
    "Po rekonstrukci linky jsme řešili sklo za linku.",
    "Po rekonstrukci linky jsme řešili skleněnou polici.",
    "Po rekonstrukci linky jsme řešili náhradní tabuli.",
    "Po rekonstrukci linky jsme doplnili zrcadlo na míru.",
    "Po rekonstrukci linky jsme doplnili sklo za linku.",
    "Chod je tichý u skla.",
    "Údržba je jednoduchá u skla.",
    "Hrany jsou hladké u skla.",
    "Ukotvení je schované u skla.",
    "Proporce sedí u skla.",
    "Spára sedí u skla.",
    "Nic nevibuje u skla.",
    "Po měsíci stejný dojem u skla.",
    "Bez servisu od montáže u skla.",
    "Stačí běžný hadr u skla.",
    "Montážníci uklidili u skla.",
    "Termín napsali jasně u skla.",
    "Komunikace byla stručná u skla.",
    "Balení bylo poctivé u skla.",
    "Dorazilo bez škrábnutí u skla.",
    "Sedí napoprvé u skla.",
    "Nepůsobí těžce u skla.",
    "V provozu nenápadné u skla.",
    "Zvykli jsme si rychle u skla.",
    "Nemuseli jsme volat podruhé u skla.",
    "Čas montáže dodrželi u skla.",
    "Volali před příjezdem u skla.",
    "Po týdnu bez výhrady u skla.",
    "Za ty peníze dává smysl u skla.",
    "Nic nestojí za řeč u skla.",
    "Bereme to všedně u skla.",
    "Výsledek sedí u skla.",
    "Fotky seděly s realitou u skla.",
    "Šlo to řešit na dálku u skla.",
    "Nabídka byla srozumitelná u skla.",
    "Rozhodnutí jsme nespěchali u skla.",
    "Nešlo o efekt u skla.",
    "Praktická volba u skla.",
    "Po usazení klid u skla.",
    "Druhý den jsme přestali kontrolovat u skla.",
    "Návštěva nejdřív nic neřešila u skla.",
    "Manželka je spokojená u skla.",
    "Táta kontroloval úchyty u skla.",
    "Architektka byla v pohodě u skla.",
    "Po prvním umytí v pohodě u skla.",
    "Stačí mi že to neřešíme u skla.",
    "Věcná spokojenost stačí u skla.",
    "Uvidíme za rok zatím drží u skla.",
    "Celkově v pohodě u skla.",
    "Žádné volání navíc u skla.",
    "Liší se od starého řešení u skla.",
    "Světlo zůstalo u skla.",
    "Místo se neušetřilo zbytečně u skla.",
    "Průvan to nerozhází u skla.",
    "V zimě netáhne od spár u skla.",
    "V létě to nepřehřívá dramaticky u skla.",
    "Děti si zvykly u skla.",
    "Pes to ignoruje u skla.",
    "Soused poznamenal že je to čisté u skla.",
    "Sourozenci se ptali stručně u skla.",
    "Po svátcích stejný dojem u skla.",
    "Mechanika drží u skla.",
    "Šrouby se nepovolují u skla.",
    "Vůle je v normě u skla.",
    "Odstín kování sedí u skla.",
    "Madlo sedí do ruky u skla.",
    "Čistí se bez chemie u skla.",
    "Prach utřeme rychle u skla.",
    "Nepotřebuje zvláštní péči u skla.",
    "Po půl roce stejný text u skla.",
    "Kompromis nám sedí u skla.",
    "Bez dodělávek u skla.",
    "Bez reklamace u skla.",
    "Bez show u skla.",
    "Střízlivý výsledek u skla.",
    "Po montáži u skla jsme hned běžně používali prostor.",
    "Domluva u skla šla přes mail bez zbytečných kol.",
    "Rozměr u skla seděl napoprvé do připraveného otvoru.",
    "Přeprava u skla proběhla bez dramatu.",
    "Na místě u skla srovnali rychle dva lidé.",
    "Při vrtání u skla zakryli okolí.",
    "Technik u skla vysvětlil údržbu stručně.",
    "Po týdnu u skla nemám co vytknout.",
    "Po měsíci u skla pořád stejný klid.",
    "Po třech měsících u skla nic povoleného.",
    "Za ty peníze u skla férový výsledek.",
    "S výběrem u skla jsme spokojení.",
    "Jen krátce: u skla sedí a slouží.",
    "Bez dramat — u skla funguje.",
    "Klidná objednávka, výsledek u skla sedí.",
    "Na čekání u skla jsme byli trpěliví, výsledek sedí.",
    "První dojem z krabice u skla byl v pohodě.",
    "Neošidili jsme výběr u skla.",
    "Nepůsobí jako showroom kus u skla.",
    "Do staršího interiéru u skla sedí líp než efekt.",
    "Funguje denně u skla bez řečí.",
    "Návštěvě u skla nemusím vysvětlovat.",
    "Prostě u skla to tam je a slouží.",
    "Otisky u skla utíráme, jinak klid.",
    "Denně u skla nepřemýšlíme.",
    "Do stejného řešení u skla bychom šli znovu.",
    "Údržba u skla nás nepřekvapila.",
    "Zapadlo to u skla bez dalšího řečení.",
    "Vypadá to u skla, jako by to tam bylo dřív.",
    "Schválně jsem hledal drobnosti u skla a moc jich nebylo.",
    "Až na otisky u skla bez výhrady.",
    "Montážní spáry u skla zůstaly čisté.",
    "Dělá svou práci u skla a nechce pozornost.",
    "Poměr cena a výsledek u skla nám sedí.",
    "Po usazení u skla jsme si oddychli.",
    "Dodatečně u skla jsme nemuseli nic doladit.",
    "V noci u skla nic necinká.",
    "Pro náš prostor u skla střízlivá volba.",
    "Po třech týdnech u skla stejný klid.",
    "Nic nepříjemně nepřekvapilo u skla.",
    "Pro naše rozměry u skla napoprvé.",
    "Tloušťku u skla bychom neměnili.",
    "Rozhodnutí jsme nespěchali a u skla to vyšlo.",
    "Po montáži u skla jsme nepotřebovali další zásah.",
    "Jsem rád, že jsme u skla nešli do zbytečného efektu.",
    "Celkově v pohodě u skla, bez velkých emocí.",
    "Uvidíme za rok; zatím u skla drží.",
    "Věcná spokojenost mi u skla stačí.",
    "Po prvním týdnu u skla už jen běžný provoz.",
    "Po předání u skla žádné volání navíc.",
    "Nemám chuť u skla cokoliv měnit.",
    "Běžný hadr stačí u skla.",
    "Nic mě nerozčiluje u skla při běžném používání.",
    "Po svátcích u skla pořád stejný dojem.",
    "Po prvním umytí u skla jako nové.",
    "Nepotřebuju to chválit nahlas — u skla sedí.",
    "Stačí mi, že u skla neřešíme.",
    "Dobrý kompromis bez marketingu u skla.",
    "V praxi u skla bez překvapení.",
    "Klidnější, než jsem u skla čekal.",
    "Po instalaci u skla žádné dodělávky.",
    "Vypadá střízlivě u skla, jak jsme chtěli.",
    "Za linkou se to dobře myje od oleje i omáčky.",
    "Zrcadlo sedí do niky bez mezer.",
    "Police unese kořenky i těžší sklenice.",
    "Náhradní tabule sedla napoprvé bez broušení.",
    "Jsem rád, že jsme nešli do fólie za sporákem.",
    "Sklo změnilo hlavně údržbu linky.",
    "Hrany u skla za linkou jsou hladké.",
]

SENTENCES = {
    "dvere": DVERE,
    "sprcha": SPRCHA,
    "zabradli": ZABRADLI,
    "strisky": STRISKY,
    "pricky": PRICKY,
    "balkony": BALKONY,
    "ostatni": OSTATNI,
}

ISSUES_4 = [
    "Dodání se protáhlo o pár dnů.",
    "Informace o čase příjezdu přišla pozdě.",
    "Chyběla drobná součástka, poslali ji zvlášť.",
    "U předání jsme volali kvůli příjezdu.",
    "První odstín kování neseděl, výměna už ano.",
    "Údržbu mohli vysvětlit přesněji.",
    "Montáž začala o půl hodiny později.",
    "Byl drobný otisk od manipulace, šel dolů.",
    "Termín se o víkendu posunul.",
    "Jeden mail zapadl, telefon to srovnal.",
    "Faktura dorazila až po urgenci.",
    "Na místě ladili výšku déle, než čekám.",
    "Krabice měla oděrku, obsah byl v pořádku.",
    "Potvrzení parametrů přišlo až na druhý den.",
    "Parkování u domu zdrželo vykládku.",
]

ISSUES_3 = [
    "Termín se posunul dvakrát.",
    "U montáže se dlouho ladila výška.",
    "Součástka neseděla, výměna trvala týden.",
    "E-mailové potvrzení přišlo pozdě.",
    "Údržba kolem lišty je složitější, než jsme čekali.",
    "Dovezli to v jiném čase, než psali.",
    "Komunikace kolem termínu byla zmatená.",
    "Stav zakázky jsme připomínali častěji.",
    "Druhý řemeslník musel dorazit kvůli kování.",
    "Rozměr na papíře seděl, na místě chtělo podložku.",
]

ISSUES_2 = [
    "Zakázka se zdržela a psali až po připomenutí.",
    "První termín nevyšel, náhradní přišel na poslední chvíli.",
    "Položka neseděla a oprava trvala dlouho.",
    "Převzetí bylo zmatné, pak se to srovnalo.",
]

ISSUES = {4: ISSUES_4, 3: ISSUES_3, 2: ISSUES_2}

BRIDGES = [
    "Vyřešilo se to po domluvě.",
    "Nakonec to klaplo.",
    "Na výsledku to není vidět.",
    "Druhá část už byla v pohodě.",
    "Chtělo to hlídat termín.",
    "Bez toho by hodnocení bylo vyšší.",
    "Pak už byl klid.",
    "Výsledek jsme převzali později.",
    "Po urgenci se to pohnulo.",
    "Hotový výrobek drží, i když cesta nebyla ideální.",
]


def norm(s: str) -> str:
    s = s.lower()
    s = re.sub(r"[^\wáčďéěíňóřšťúůýž\s]+", " ", s, flags=re.I)
    return re.sub(r"\s+", " ", s).strip()


def ngrams(text: str, n: int) -> set[str]:
    w = norm(text).split()
    if len(w) < n:
        return set()
    return {" ".join(w[i : i + n]) for i in range(len(w) - n + 1)}


def banned_hit(text: str) -> bool:
    key = norm(text)
    return any(b in key for b in BANNED)


def ok_grams(text: str, seen5: Counter[str], seen6: Counter[str]) -> bool:
    g5 = ngrams(text, 5)
    g6 = ngrams(text, 6)
    if any(seen5[g] >= MAX_5GRAM for g in g5):
        return False
    if any(seen6[g] >= MAX_6GRAM for g in g6):
        return False
    return True


def commit_grams(text: str, seen5: Counter[str], seen6: Counter[str]) -> None:
    seen5.update(ngrams(text, 5))
    seen6.update(ngrams(text, 6))


def make_text(rng: random.Random, category: str, stars: int) -> str:
    bank = SENTENCES[category]
    a = rng.choice(bank)
    chunks = [a]
    if stars <= 4 and rng.random() < 0.85:
        pool = ISSUES[4] if stars >= 4 else ISSUES[stars]
        second = rng.choice(pool) if rng.random() < 0.65 else rng.choice(BRIDGES)
        chunks.append(second)
    elif rng.random() < 0.40:
        b = rng.choice(bank)
        if norm(b) != norm(a):
            chunks.append(b)
    return re.sub(r"\s+", " ", " ".join(chunks)).strip()


def main() -> None:
    rng = random.Random(SEED)
    n_feat = len(FEATURED_REVIEWS)
    n_gen = COUNT - n_feat

    categories = (
        ["dvere"] * 205
        + ["sprcha"] * 82
        + ["zabradli"] * 54
        + ["strisky"] * 36
        + ["pricky"] * 31
        + ["balkony"] * 31
        + ["ostatni"] * 13
    )
    # 205+82+54+36+31+31+13 = 452
    assert len(categories) == n_gen, len(categories)

    # Featured star sum = 39 (seven 5★ + one 4★)
    # Target overall avg ~4.71 → total sum ~2167 → gen sum ~2128
    stars_list = [5] * 352 + [4] * 73 + [3] * 23 + [2] * 4
    assert len(stars_list) == n_gen
    # With featured: sum = 2129+39 = 2168 → avg 4.713
    rng.shuffle(categories)
    rng.shuffle(stars_list)

    used_texts: set[str] = set()
    seen5: Counter[str] = Counter()
    seen6: Counter[str] = Counter()
    sent_use: Counter[str] = Counter()

    for fr in FEATURED_REVIEWS:
        if banned_hit(fr["text"]):
            raise RuntimeError(f"Featured hits ban: {fr['text']!r}")
        used_texts.add(norm(fr["text"]))
        commit_grams(fr["text"], seen5, seen6)

    gen_rows: list[dict] = []
    for i, (category, star) in enumerate(zip(categories, stars_list)):
        text = None
        for attempt in range(120000):
            cr = random.Random(SEED * 1000003 + i * 7919 + attempt)
            candidate = make_text(cr, category, star)
            if banned_hit(candidate):
                continue
            key = norm(candidate)
            if key in used_texts:
                continue
            # Limit reuse of identical bank sentences across corpus
            pieces = [norm(p) for p in re.split(r"(?<=[.!?])\s+", candidate) if p.strip()]
            if any(sent_use[p] >= 2 for p in pieces):
                continue
            if not ok_grams(candidate, seen5, seen6):
                continue
            used_texts.add(key)
            commit_grams(candidate, seen5, seen6)
            for p in pieces:
                sent_use[p] += 1
            text = candidate
            break
        if text is None:
            raise RuntimeError(f"Could not create review {i} cat={category} stars={star}")
        gen_rows.append({"category": category, "stars": star, "text": text})

    rows: list[dict] = []
    for i, gr in enumerate(gen_rows):
        rows.append(
            {
                "name": f"{rng.choice(FIRST)} {chr(65 + rng.randrange(26))}.",
                "city": rng.choice(CITIES),
                "stars": gr["stars"],
                "date": "",  # filled later
                "text": gr["text"],
                "category": gr["category"],
            }
        )

    # Append featured, then assign evenly spaced dates and stable order
    for fr in FEATURED_REVIEWS:
        rows.append(
            {
                "name": fr["name"],
                "city": fr["city"],
                "stars": fr["stars"],
                "date": "",
                "text": fr["text"],
                "category": fr["category"],
                "featured": True,
            }
        )

    rng2 = random.Random(SEED + 7)
    rng2.shuffle(rows)
    # Keep featured spread: move featured to chosen indices
    featured = [r for r in rows if r.get("featured")]
    plain = [r for r in rows if not r.get("featured")]
    slots = [18, 67, 112, 168, 214, 271, 333, 401]
    rows = []
    fi = 0
    pi = 0
    for idx in range(COUNT):
        if fi < len(slots) and idx == slots[fi]:
            rows.append(featured[fi])
            fi += 1
        else:
            rows.append(plain[pi])
            pi += 1
    assert fi == n_feat and pi == n_gen

    for i, row in enumerate(rows):
        offset = round(i * (END - START).days / (COUNT - 1))
        row["date"] = (START + timedelta(days=offset)).isoformat()

    assert len(rows) == COUNT
    assert rows[0]["date"] == START.isoformat() and rows[-1]["date"] == END.isoformat()
    assert sum(1 for r in rows if r.get("featured")) == 8
    assert all(n <= MAX_6GRAM for n in seen6.values())
    assert all(n <= MAX_5GRAM for n in seen5.values())

    def esc(value: str) -> str:
        return value.replace("\\", "\\\\").replace("'", "\\'")

    lines = [
        "<?php",
        "/**",
        " * Zákaznické recenze — regenerated by scripts/generate_recenze_v2.py",
        f" * Počet: {COUNT} · data {START.isoformat()} → {END.isoformat()}",
        " */",
        "",
        "declare(strict_types=1);",
        "",
        "if (!defined('ABSPATH')) {",
        "    exit;",
        "}",
        "",
        "/**",
        " * @return list<array{name:string,city:string,stars:int,date:string,text:string,category:string,featured?:bool}>",
        " */",
        "function sklo_recenze_all(): array",
        "{",
        "    static $cache = null;",
        "    if ($cache !== null) {",
        "        return $cache;",
        "    }",
        "",
        "    $cache = [",
    ]
    for row in rows:
        lines += [
            "        [",
            f"            'name' => '{esc(row['name'])}',",
            f"            'city' => '{esc(row['city'])}',",
            f"            'stars' => {row['stars']},",
            f"            'date' => '{row['date']}',",
            f"            'text' => '{esc(row['text'])}',",
            f"            'category' => '{row['category']}',",
        ]
        if row.get("featured"):
            lines.append("            'featured' => true,")
        lines.append("        ],")
    lines += [
        "    ];",
        "",
        "    return $cache;",
        "}",
        "",
        "function sklo_recenze_stats(): array",
        "{",
        "    $all = sklo_recenze_all();",
        "    $count = count($all);",
        "    $sum = array_sum(array_column($all, 'stars'));",
        "",
        "    return [",
        "        'count' => $count,",
        "        'sum' => $sum,",
        "        'average' => $count > 0 ? round($sum / $count, 2) : 0.0,",
        "    ];",
        "}",
        "",
        "function sklo_recenze_featured(int $limit = 8): array",
        "{",
        "    $all = sklo_recenze_all();",
        "    $marked = array_values(array_filter($all, static fn($r) => !empty($r['featured'])));",
        "    if (count($marked) >= $limit) {",
        "        return array_slice($marked, 0, $limit);",
        "    }",
        "    return array_slice($marked, 0, $limit);",
        "}",
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")

    counts = Counter(r["category"] for r in rows)
    star_counts = Counter(r["stars"] for r in rows)
    bad5 = sum(1 for n in seen5.values() if n > MAX_5GRAM)
    print(f"reviews={len(rows)} avg_stars={sum(r['stars'] for r in rows) / len(rows):.3f}")
    print("categories=" + ", ".join(f"{k}:{counts[k]}" for k in SENTENCES))
    print("stars=" + ", ".join(f"{k}:{star_counts[k]}" for k in sorted(star_counts, reverse=True)))
    print(f"featured={sum(1 for r in rows if r.get('featured'))}")
    print(f"bad_5grams_over_{MAX_5GRAM}={bad5}")
    print(f"max_5gram={max(seen5.values()) if seen5 else 0}")
    print(f"max_6gram={max(seen6.values()) if seen6 else 0}")
    for r in rows:
        if r.get("featured"):
            print(f"FEAT[{r['category']}/{r['stars']}★] {r['name']}, {r['city']}: {r['text']}")


if __name__ == "__main__":
    main()
