<?php
/**
 * Zákaznické recenze — generováno scripts/import_recenze.py
 * Počet: 182 · data 2021-08-01 → 2026-08-01
 */

declare(strict_types=1);

if (!defined('ABSPATH')) {
    exit;
}

/**
 * @return list<array{name:string,city:string,stars:int,date:string,text:string,category:string}>
 */
function sklo_recenze_all(): array
{
    static $cache = null;
    if ($cache !== null) {
        return $cache;
    }

    $cache = [
        [
            'name' => 'Karolína V.',
            'city' => 'Brno',
            'stars' => 5,
            'date' => '2021-08-01',
            'text' => 'Dveře jsem objednala na doporučení kamarádky a nelituji. Přišly přesně jak jsem si vybrala, sklo je krásné a celý byt to posunulo o level výš.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Stanislav H.',
            'city' => 'Praha',
            'stars' => 5,
            'date' => '2021-08-11',
            'text' => 'Objednal jsem posuvné dveře do obýváku. Zaměřoval jsem poprvé v životě, trochu jsem se bál, ale návod je fakt srozumitelný. Dveře sedí perfektně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Růžena M.',
            'city' => 'Ostrava',
            'stars' => 4,
            'date' => '2021-08-21',
            'text' => 'Dodací lhůta byla o týden delší než jsem čekala. Napsala jsem jim a omluvili se, vysvětlili proč a dveře dorazily v pořádku. Kvalita je dobrá, příště bych objednala znovu.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Vladimír K.',
            'city' => 'Liberec',
            'stars' => 5,
            'date' => '2021-08-31',
            'text' => 'Rekonstruoval jsem celý dům a skleněné dveře byly věc, u které jsem nejvíc váhal. Nakonec jsem rád že jsem to tady objednal. Vypadají skvěle a cena byla rozumná.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Dagmar P.',
            'city' => 'Plzeň',
            'stars' => 5,
            'date' => '2021-09-10',
            'text' => 'Komunikace byla příjemná od začátku do konce. Poradili mi s výběrem, odpověděli na všechny moje dotazy a dveře dorazily v pořádku. Doporučuju.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Miroslav Š.',
            'city' => 'Olomouc',
            'stars' => 5,
            'date' => '2021-09-20',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Trvalo mi to půl dne, ale výsledek stojí za to. Dveře jsou krásné a pevné.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ivana B.',
            'city' => 'Zlín',
            'stars' => 4,
            'date' => '2021-10-01',
            'text' => 'Při objednávce jsem si spletla rozměry a napsala jsem jim hned jak jsem to zjistila. Opravili to ještě před výrobou, takže žádný problém. Fajn přístup.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Jaroslav N.',
            'city' => 'Pardubice',
            'stars' => 5,
            'date' => '2021-10-11',
            'text' => 'Sprchový kout vypadá úžasně. Manželka je nadšená a to je pro mě hlavní měřítko úspěchu 😄',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Lucie F.',
            'city' => 'Hradec Králové',
            'stars' => 5,
            'date' => '2021-10-21',
            'text' => 'Objednala jsem dveře do koupelny a ložnice najednou. Přišly spolu, vše bylo pečlivě zabalené a nic nebylo poškozené. Montáž zvládl manžel sám za odpoledne.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Bedřich T.',
            'city' => 'Jihlava',
            'stars' => 5,
            'date' => '2021-10-31',
            'text' => 'Starý byt, nerovné zdi, nestandardní otvor. Napsal jsem jim to předem a poradili mi jak na to. Dveře sedí, vypadají moderně a já jsem spokojený.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Soňa K.',
            'city' => 'Tábor',
            'stars' => 5,
            'date' => '2021-11-10',
            'text' => 'Hledala jsem dveře do malého bytu kde záleží na každém centimetru. Pomohli mi vybrat správný typ a rozměr. Výsledek je přesně co jsem chtěla.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Antonín R.',
            'city' => 'Kladno',
            'stars' => 5,
            'date' => '2021-11-20',
            'text' => 'Objednal jsem zábradlí na schodiště. Přišlo v pořádku, montáž jsem zvládl sám. Vypadá to moc hezky, schodiště dostalo úplně jiný charakter.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Marcela D.',
            'city' => 'Opava',
            'stars' => 4,
            'date' => '2021-11-30',
            'text' => 'Po dodání mi chyběl jeden kotevní šroub. Napsala jsem jim a druhý den mi ho poslali poštou. Maličkost, ale vyřešili to bez řečí.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Libor V.',
            'city' => 'Karviná',
            'stars' => 5,
            'date' => '2021-12-10',
            'text' => 'Objednal jsem bez montáže, ale zjistil jsem že na to nemám nářadí ani zkušenosti. Zavolal jsem jim a domluvili jsme montáž dodatečně. Kluci přijeli, bylo to rychlé a profesionální.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Naděžda H.',
            'city' => 'Znojmo',
            'stars' => 5,
            'date' => '2021-12-20',
            'text' => 'Krásné dveře, rychlé dodání, příjemná komunikace. Víc toho nepotřebuji 😊',
            'category' => 'dvere',
        ],
        [
            'name' => 'Přemysl B.',
            'city' => 'Chomutov',
            'stars' => 5,
            'date' => '2021-12-30',
            'text' => 'Dělal jsem to poprvé a bál jsem se že něco pokazím při zaměřování. Ale jejich návod je tak dobrý, že jsem to zvládl bez problémů. Dveře sedí na milimetr.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Věra S.',
            'city' => 'Kolín',
            'stars' => 5,
            'date' => '2022-01-09',
            'text' => 'Objednala jsem sprchový kout a dveře do ložnice. Oboje přišlo najednou, vše v pořádku. Koupelna i ložnice vypadají skvěle.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Zbyněk M.',
            'city' => 'Mladá Boleslav',
            'stars' => 4,
            'date' => '2022-01-20',
            'text' => 'Dveře přišly o pár dní později než bylo v potvrzení. Napsal jsem jim, omluvili se a vysvětlili situaci. Dveře jsou kvalitní, takže to odpouštím.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Renata L.',
            'city' => 'Přerov',
            'stars' => 5,
            'date' => '2022-01-30',
            'text' => 'Bydlím sama a bála jsem se jak zvládnu montáž. Objednala jsem ji rovnou s dveřmi. Kluci přijeli, byli milí a pracovali čistě. Doporučuju.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ctibor J.',
            'city' => 'Ústí nad Labem',
            'stars' => 5,
            'date' => '2022-02-09',
            'text' => 'Hledal jsem dveře bez rámu do moderního bytu. Přesně to co jsem chtěl. Vypadají skvěle a sklo je pevné.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Blanka N.',
            'city' => 'Frýdek-Místek',
            'stars' => 5,
            'date' => '2022-02-19',
            'text' => 'Objednala jsem poprvé a nevěděla jsem co čekat. Celý proces byl jednoduchý, komunikace rychlá a dveře jsou přesně takové jaké jsem chtěla.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Oldřich P.',
            'city' => 'Havířov',
            'stars' => 5,
            'date' => '2022-03-01',
            'text' => 'Montáž jsem dělal sám, zasekl jsem se u jednoho detailu a zavolal jsem jim. Poradili mi hned a bez povyku. Dveře fungují perfektně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Taťána K.',
            'city' => 'Most',
            'stars' => 4,
            'date' => '2022-03-11',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Vyfotila jsem to a napsala jim. Do deseti dní mi poslali náhradu. Spokojená jsem, jen to mohlo přijít bez škrábanců 😄',
            'category' => 'dvere',
        ],
        [
            'name' => 'Rostislav H.',
            'city' => 'Teplice',
            'stars' => 5,
            'date' => '2022-03-21',
            'text' => 'Zábradlí na balkon vypadá skvěle. Sousedé se ptají kde jsem to bral. Montáž jsem zvládl sám za sobotu.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Jarmila V.',
            'city' => 'Děčín',
            'stars' => 5,
            'date' => '2022-03-31',
            'text' => 'Rekonstruovala jsem koupelnu a sprchový kout byl poslední věc. Tady jsem to vyřídila nejrychleji a nejlépe. Doporučuju každému.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Radovan B.',
            'city' => 'Chomutov',
            'stars' => 5,
            'date' => '2022-04-10',
            'text' => 'Objednal jsem dveře na míru do nestandardního otvoru. Vše proběhlo bez problémů, dveře sedí přesně a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Milena T.',
            'city' => 'Jablonec nad Nisou',
            'stars' => 5,
            'date' => '2022-04-20',
            'text' => 'Krásné sklo, solidní zpracování, rychlé dodání. Přesně co jsem hledala a za rozumnou cenu.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Bohuslav K.',
            'city' => 'Liberec',
            'stars' => 4,
            'date' => '2022-04-30',
            'text' => 'Objednal jsem bez montáže a pak jsem zjistil že zeď je z materiálu do kterého se mi nedaří kotvit. Zavolal jsem jim a poradili mi jak na to. Nakonec jsem to zvládl sám.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Světlana M.',
            'city' => 'Prostějov',
            'stars' => 5,
            'date' => '2022-05-10',
            'text' => 'Dveře do obýváku i ložnice. Oboje vypadá skvěle, sklo je čisté a pevné. Celý byt to posunulo.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Cyril D.',
            'city' => 'Kroměříž',
            'stars' => 5,
            'date' => '2022-05-21',
            'text' => 'Objednal jsem zábradlí na schodiště a stříšku nad vchod. Oboje přišlo najednou, montáž jsem zvládl sám. Dům vypadá úplně jinak.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Libuše H.',
            'city' => 'Uherské Hradiště',
            'stars' => 5,
            'date' => '2022-05-31',
            'text' => 'Dávala jsem to jako vánoční dárek manželovi — nové dveře do pracovny. Přišly včas, manžel je nadšený. Skvělý nápad 😄',
            'category' => 'dvere',
        ],
        [
            'name' => 'Drahomír S.',
            'city' => 'Vsetín',
            'stars' => 5,
            'date' => '2022-06-10',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Trvalo mi to déle než jsem čekal, ale výsledek je skvělý. Dveře jsou pevné a vypadají moderně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Alžběta P.',
            'city' => 'Valašské Meziříčí',
            'stars' => 4,
            'date' => '2022-06-20',
            'text' => 'Dodací lhůta byla delší než jsem čekala, ale dveře přišly v pořádku a jsou krásné. Příště bych si nechala víc času na plánování.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Bronislav K.',
            'city' => 'Nový Jičín',
            'stars' => 5,
            'date' => '2022-06-30',
            'text' => 'Koupelna vypadá jako z katalogu. Sprchový kout je přesně takový jaký jsem chtěl a montáž proběhla bez problémů.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Hedvika N.',
            'city' => 'Frýdek-Místek',
            'stars' => 5,
            'date' => '2022-07-10',
            'text' => 'Objednávala jsem poprvé a měla jsem spoustu dotazů. Odpověděli na všechny, trpělivě a bez shonu. Dveře jsou krásné.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Vladimíra T.',
            'city' => 'Třinec',
            'stars' => 5,
            'date' => '2022-07-20',
            'text' => 'Posuvné dveře do kuchyně jsou přesně co jsem hledala. Ušetřily místo a vypadají skvěle. Montáž zvládl manžel sám.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Lumír B.',
            'city' => 'Havířov',
            'stars' => 5,
            'date' => '2022-07-30',
            'text' => 'Objednal jsem bez montáže, ale pak jsem zjistil že na to nestačím. Zavolal jsem jim a domluvili jsme montáž dodatečně. Kluci přijeli druhý den, bylo to rychlé a čisté.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Štěpánka V.',
            'city' => 'Opava',
            'stars' => 5,
            'date' => '2022-08-09',
            'text' => 'Dveře do koupelny i obýváku. Oboje přišlo v pořádku a vypadá skvěle. Celý byt to proměnilo.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Evžen M.',
            'city' => 'Ostrava',
            'stars' => 4,
            'date' => '2022-08-19',
            'text' => 'Po montáži mi dveře po čase začaly trochu vrzat. Napsal jsem jim, poslali mi video kde mám co seřídit. Zvládl jsem to sám za chvíli. Dobrý servis.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Kateřina D.',
            'city' => 'Brno',
            'stars' => 5,
            'date' => '2022-08-29',
            'text' => 'Hledala jsem dveře do malého bytu a bála jsem se že nic nenajdu. Ale mají opravdu velký výběr a poradili mi s výběrem. Výsledek je skvělý.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Augustin H.',
            'city' => 'Praha',
            'stars' => 5,
            'date' => '2022-09-09',
            'text' => 'Objednal jsem skleněné příčky do kanceláře. Přišly v pořádku, montáž proběhla hladce a kancelář vypadá profesionálně.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Růžena K.',
            'city' => 'Plzeň',
            'stars' => 5,
            'date' => '2022-09-19',
            'text' => 'Krásné dveře, rychlé dodání, příjemná komunikace. Co víc si přát.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ladislav N.',
            'city' => 'Liberec',
            'stars' => 4,
            'date' => '2022-09-29',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Vyfotil jsem to a poslal jim. Omluvili se a do týdne mi poslali nové sklo. Vyřešeno bez problémů.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Marta S.',
            'city' => 'Olomouc',
            'stars' => 5,
            'date' => '2022-10-09',
            'text' => 'Objednala jsem sprchový kout walk-in. Vypadá skvěle, koupelna dostala úplně jiný charakter. Montáž zvládl manžel sám.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Zdeněk V.',
            'city' => 'Zlín',
            'stars' => 5,
            'date' => '2022-10-19',
            'text' => 'Objednal jsem zábradlí na balkon. Přišlo v pořádku, montáž jsem zvládl sám za sobotu. Balkon vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Irena B.',
            'city' => 'Pardubice',
            'stars' => 5,
            'date' => '2022-10-29',
            'text' => 'Rekonstruovala jsem celý byt a skleněné dveře byly nejlepší rozhodnutí. Světlo prochází celým bytem a je to úplně jiný pocit.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ctibor M.',
            'city' => 'Hradec Králové',
            'stars' => 5,
            'date' => '2022-11-08',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Návod je srozumitelný a když jsem si nevěděl rady, zavolal jsem a poradili mi hned.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Božena T.',
            'city' => 'Jihlava',
            'stars' => 5,
            'date' => '2022-11-18',
            'text' => 'Jsem starší a bála jsem se celého procesu. Ale syn mi pomohl s objednávkou a komunikaci jsem vedla sama. Byli trpěliví a milí. Dveře jsou nádherné.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Přemysl K.',
            'city' => 'Tábor',
            'stars' => 4,
            'date' => '2022-11-28',
            'text' => 'Objednal jsem bez montáže, ale zasekl jsem se u kotvení. Zavolal jsem jim a chlapík mi to vysvětlil po telefonu. Oceňuju že poradí i těm co si to dělají sami.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Věnceslava H.',
            'city' => 'Kladno',
            'stars' => 5,
            'date' => '2022-12-08',
            'text' => 'Dveře do ložnice jsou přesně co jsem chtěla. Sklo je matné, světlo prochází ale soukromí je zachované. Skvělý výběr.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Miroslav D.',
            'city' => 'Opava',
            'stars' => 5,
            'date' => '2022-12-18',
            'text' => 'Objednal jsem dveře a zábradlí najednou. Oboje přišlo v pořádku a vypadá skvěle. Dům dostalo nový charakter.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Anežka V.',
            'city' => 'Karviná',
            'stars' => 5,
            'date' => '2022-12-29',
            'text' => 'Objednávala jsem poprvé a nevěděla jsem co čekat. Celý proces byl jednoduchý a dveře jsou přesně takové jaké jsem chtěla.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Bohumil S.',
            'city' => 'Znojmo',
            'stars' => 5,
            'date' => '2023-01-08',
            'text' => 'Objednal jsem dveře jako vánoční dárek pro celou rodinu — nové dveře do obýváku. Přišly včas a rodina je nadšená.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Taťána N.',
            'city' => 'Chomutov',
            'stars' => 4,
            'date' => '2023-01-18',
            'text' => 'Dodací lhůta byla trochu delší, ale dveře přišly v pořádku. Kvalita je dobrá a vypadají hezky. Příště bych objednala znovu.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radoslav B.',
            'city' => 'Kolín',
            'stars' => 5,
            'date' => '2023-01-28',
            'text' => 'Objednal jsem posuvné dveře do kuchyně. Ušetřily místo a vypadají skvěle. Montáž zvládl kamarád za odpoledne.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Milada K.',
            'city' => 'Mladá Boleslav',
            'stars' => 5,
            'date' => '2023-02-07',
            'text' => 'Krásné dveře, solidní zpracování, rychlé dodání. Přesně co jsem hledala.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Jaromír T.',
            'city' => 'Přerov',
            'stars' => 5,
            'date' => '2023-02-17',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Trvalo mi to déle než jsem čekal, ale výsledek je skvělý.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Stanislava H.',
            'city' => 'Ústí nad Labem',
            'stars' => 5,
            'date' => '2023-02-27',
            'text' => 'Sprchový kout walk-in je přesně co jsem chtěla. Koupelna vypadá moderně a prostorně. Doporučuju.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Vladimír P.',
            'city' => 'Frýdek-Místek',
            'stars' => 5,
            'date' => '2023-03-09',
            'text' => 'Objednal jsem dveře do pracovny. Přišly v pořádku, montáž jsem zvládl sám. Pracovna vypadá profesionálně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Libuše K.',
            'city' => 'Havířov',
            'stars' => 4,
            'date' => '2023-03-19',
            'text' => 'Po montáži mi dveře trochu drhnuly. Napsala jsem jim a poslali mi kde mám co seřídit. Zvládla jsem to sama. Dobrý servis.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Drahomíra N.',
            'city' => 'Most',
            'stars' => 5,
            'date' => '2023-03-29',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle. Koupelna dostala nový charakter.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Alois V.',
            'city' => 'Teplice',
            'stars' => 5,
            'date' => '2023-04-08',
            'text' => 'Zábradlí na schodiště vypadá skvěle. Montáž jsem zvládl sám za sobotu. Schodiště dostalo úplně jiný charakter.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Jaroslava B.',
            'city' => 'Děčín',
            'stars' => 5,
            'date' => '2023-04-18',
            'text' => 'Objednala jsem dveře a sprchový kout najednou. Oboje přišlo v pořádku a vypadá skvěle. Byt se proměnil.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Radovan M.',
            'city' => 'Jablonec nad Nisou',
            'stars' => 5,
            'date' => '2023-04-29',
            'text' => 'Objednal jsem bez montáže, ale pak jsem zjistil že zeď je z jiného materiálu než jsem čekal. Zavolal jsem jim a poradili mi jak na to. Zvládl jsem to nakonec sám.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Milena D.',
            'city' => 'Prostějov',
            'stars' => 5,
            'date' => '2023-05-09',
            'text' => 'Krásné dveře, rychlé dodání, příjemná komunikace. Doporučuju každému.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Cyril H.',
            'city' => 'Kroměříž',
            'stars' => 4,
            'date' => '2023-05-19',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Vyfotil jsem to a napsala jim. Do týdne mi poslali náhradu. Spokojený jsem.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Světlana K.',
            'city' => 'Uherské Hradiště',
            'stars' => 5,
            'date' => '2023-05-29',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle. Ložnice dostala nový charakter.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Lumír N.',
            'city' => 'Vsetín',
            'stars' => 5,
            'date' => '2023-06-08',
            'text' => 'Objednal jsem zábradlí na balkon. Montáž jsem zvládl sám. Balkon vypadá moderně.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Štěpánka B.',
            'city' => 'Valašské Meziříčí',
            'stars' => 5,
            'date' => '2023-06-18',
            'text' => 'Rekonstruovala jsem koupelnu a sprchový kout byl nejlepší rozhodnutí. Vypadá skvěle a montáž proběhla hladce.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Evžen K.',
            'city' => 'Nový Jičín',
            'stars' => 5,
            'date' => '2023-06-28',
            'text' => 'Objednal jsem dveře do obýváku. Přišly v pořádku, montáž jsem zvládl sám. Obývák vypadá moderně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Kateřina H.',
            'city' => 'Třinec',
            'stars' => 4,
            'date' => '2023-07-08',
            'text' => 'Objednala jsem bez montáže, ale pak jsem zjistila že na to nestačím. Zavolala jsem jim a domluvily jsme montáž dodatečně. Kluci přijeli, bylo to rychlé a čisté.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Augustin N.',
            'city' => 'Brno',
            'stars' => 5,
            'date' => '2023-07-18',
            'text' => 'Objednal jsem skleněné příčky do kanceláře. Přišly v pořádku, montáž proběhla hladce. Kancelář vypadá skvěle.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Růžena T.',
            'city' => 'Praha',
            'stars' => 5,
            'date' => '2023-07-28',
            'text' => 'Dveře do koupelny jsou přesně co jsem chtěla. Sklo je matné, soukromí je zachované. Skvělý výběr.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ladislav B.',
            'city' => 'Ostrava',
            'stars' => 5,
            'date' => '2023-08-07',
            'text' => 'Objednal jsem dveře jako vánoční dárek. Přišly včas a rodina je nadšená. Skvělý nápad.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Marta K.',
            'city' => 'Plzeň',
            'stars' => 5,
            'date' => '2023-08-18',
            'text' => 'Objednala jsem posuvné dveře do kuchyně. Ušetřily místo a vypadají skvěle. Montáž zvládl manžel sám.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Zdeněk N.',
            'city' => 'Liberec',
            'stars' => 4,
            'date' => '2023-08-28',
            'text' => 'Dodací lhůta byla o pár dní delší. Napsala jsem jim a omluvili se. Dveře jsou kvalitní, takže to odpouštím.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Irena V.',
            'city' => 'Olomouc',
            'stars' => 5,
            'date' => '2023-09-07',
            'text' => 'Objednala jsem sprchový kout. Vypadá skvěle, koupelna dostala nový charakter. Doporučuju.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Ctibor B.',
            'city' => 'Zlín',
            'stars' => 5,
            'date' => '2023-09-17',
            'text' => 'Objednal jsem zábradlí na schodiště. Montáž jsem zvládl sám. Schodiště vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Božena M.',
            'city' => 'Pardubice',
            'stars' => 5,
            'date' => '2023-09-27',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle. Ložnice se proměnila.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Přemysl N.',
            'city' => 'Hradec Králové',
            'stars' => 5,
            'date' => '2023-10-07',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Návod je srozumitelný a výsledek je skvělý.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Věnceslava K.',
            'city' => 'Jihlava',
            'stars' => 5,
            'date' => '2023-10-17',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle. Koupelna dostala nový charakter.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Miroslav H.',
            'city' => 'Tábor',
            'stars' => 4,
            'date' => '2023-10-27',
            'text' => 'Po montáži mi dveře trochu skřípaly. Napsal jsem jim a poradili mi jak seřídit. Zvládl jsem to sám. Dobrý servis.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Anežka N.',
            'city' => 'Kladno',
            'stars' => 5,
            'date' => '2023-11-06',
            'text' => 'Objednala jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle. Obývák se proměnil.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Bohumil K.',
            'city' => 'Opava',
            'stars' => 5,
            'date' => '2023-11-16',
            'text' => 'Objednal jsem dveře a zábradlí najednou. Oboje přišlo v pořádku. Dům vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Taťána V.',
            'city' => 'Karviná',
            'stars' => 5,
            'date' => '2023-11-26',
            'text' => 'Objednávala jsem poprvé a celý proces byl jednoduchý. Dveře jsou přesně takové jaké jsem chtěla.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radoslav N.',
            'city' => 'Znojmo',
            'stars' => 5,
            'date' => '2023-12-07',
            'text' => 'Objednal jsem posuvné dveře do pracovny. Ušetřily místo a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Milada B.',
            'city' => 'Chomutov',
            'stars' => 4,
            'date' => '2023-12-17',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Napsala jsem jim a do týdne mi poslali náhradu. Spokojená jsem.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Jaromír K.',
            'city' => 'Kolín',
            'stars' => 5,
            'date' => '2023-12-27',
            'text' => 'Objednal jsem sprchový kout walk-in. Koupelna vypadá moderně a prostorně. Doporučuju.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Stanislava N.',
            'city' => 'Mladá Boleslav',
            'stars' => 5,
            'date' => '2024-01-06',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Vladimír B.',
            'city' => 'Přerov',
            'stars' => 5,
            'date' => '2024-01-16',
            'text' => 'Objednal jsem bez montáže, ale pak jsem zjistil že na to nestačím. Zavolal jsem jim a domluvili jsme montáž dodatečně. Kluci přijeli, bylo to rychlé.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Libuše N.',
            'city' => 'Ústí nad Labem',
            'stars' => 5,
            'date' => '2024-01-26',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle. Koupelna se proměnila.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Drahomíra B.',
            'city' => 'Frýdek-Místek',
            'stars' => 5,
            'date' => '2024-02-05',
            'text' => 'Objednala jsem sprchový kout. Vypadá skvěle a montáž proběhla hladce.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Alois N.',
            'city' => 'Havířov',
            'stars' => 4,
            'date' => '2024-02-15',
            'text' => 'Objednal jsem bez montáže a zasekl jsem se u kotvení. Zavolal jsem jim a poradili mi. Zvládl jsem to nakonec sám.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Jaroslava K.',
            'city' => 'Most',
            'stars' => 5,
            'date' => '2024-02-25',
            'text' => 'Objednala jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle. Obývák se proměnil.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radovan N.',
            'city' => 'Teplice',
            'stars' => 5,
            'date' => '2024-03-06',
            'text' => 'Objednal jsem zábradlí na balkon. Montáž jsem zvládl sám. Balkon vypadá moderně.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Milena H.',
            'city' => 'Děčín',
            'stars' => 5,
            'date' => '2024-03-16',
            'text' => 'Objednala jsem dveře jako vánoční dárek. Přišly včas a manžel je nadšený.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Cyril N.',
            'city' => 'Jablonec nad Nisou',
            'stars' => 5,
            'date' => '2024-03-26',
            'text' => 'Objednal jsem skleněné příčky do kanceláře. Přišly v pořádku a kancelář vypadá profesionálně.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Světlana B.',
            'city' => 'Prostějov',
            'stars' => 5,
            'date' => '2024-04-06',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Lumír K.',
            'city' => 'Kroměříž',
            'stars' => 4,
            'date' => '2024-04-16',
            'text' => 'Po montáži mi dveře trochu drhnuly. Napsal jsem jim a poradili mi jak seřídit. Zvládl jsem to sám.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Štěpánka N.',
            'city' => 'Uherské Hradiště',
            'stars' => 5,
            'date' => '2024-04-26',
            'text' => 'Objednala jsem sprchový kout walk-in. Koupelna vypadá skvěle a montáž proběhla hladce.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Evžen B.',
            'city' => 'Vsetín',
            'stars' => 5,
            'date' => '2024-05-06',
            'text' => 'Objednal jsem zábradlí na schodiště. Montáž jsem zvládl sám. Schodiště vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Kateřina N.',
            'city' => 'Valašské Meziříčí',
            'stars' => 5,
            'date' => '2024-05-16',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Augustin B.',
            'city' => 'Nový Jičín',
            'stars' => 5,
            'date' => '2024-05-26',
            'text' => 'Objednal jsem posuvné dveře do obýváku. Ušetřily místo a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Růžena N.',
            'city' => 'Třinec',
            'stars' => 4,
            'date' => '2024-06-05',
            'text' => 'Objednala jsem bez montáže, ale pak jsem zjistila že na to nestačím. Zavolala jsem jim a domluvily jsme montáž dodatečně. Kluci přijeli a bylo to rychlé.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Ladislav K.',
            'city' => 'Brno',
            'stars' => 5,
            'date' => '2024-06-15',
            'text' => 'Objednal jsem dveře do pracovny. Přišly v pořádku a pracovna vypadá profesionálně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Marta N.',
            'city' => 'Praha',
            'stars' => 5,
            'date' => '2024-06-25',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle. Ložnice se proměnila.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Zdeněk B.',
            'city' => 'Ostrava',
            'stars' => 5,
            'date' => '2024-07-05',
            'text' => 'Objednal jsem sprchový kout. Koupelna vypadá moderně. Doporučuju.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Irena N.',
            'city' => 'Plzeň',
            'stars' => 5,
            'date' => '2024-07-15',
            'text' => 'Objednala jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ctibor K.',
            'city' => 'Liberec',
            'stars' => 4,
            'date' => '2024-07-26',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Vyfotil jsem to a napsala jim. Do týdne mi poslali náhradu.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Božena B.',
            'city' => 'Olomouc',
            'stars' => 5,
            'date' => '2024-08-05',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Přemysl V.',
            'city' => 'Zlín',
            'stars' => 5,
            'date' => '2024-08-15',
            'text' => 'Objednal jsem zábradlí na balkon. Montáž jsem zvládl sám. Balkon vypadá moderně.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Věnceslava N.',
            'city' => 'Pardubice',
            'stars' => 5,
            'date' => '2024-08-25',
            'text' => 'Objednala jsem sprchový kout walk-in. Koupelna vypadá skvěle.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Miroslav K.',
            'city' => 'Hradec Králové',
            'stars' => 5,
            'date' => '2024-09-04',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Výsledek je skvělý.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Anežka B.',
            'city' => 'Jihlava',
            'stars' => 4,
            'date' => '2024-09-14',
            'text' => 'Po montáži mi dveře trochu skřípaly. Napsal jsem jim a poradili mi jak seřídit. Zvládla jsem to sama.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Bohumil N.',
            'city' => 'Tábor',
            'stars' => 5,
            'date' => '2024-09-24',
            'text' => 'Objednal jsem dveře a sprchový kout najednou. Oboje přišlo v pořádku a vypadá skvěle.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Taťána B.',
            'city' => 'Kladno',
            'stars' => 5,
            'date' => '2024-10-04',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle. Ložnice se proměnila.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radoslav B.',
            'city' => 'Opava',
            'stars' => 5,
            'date' => '2024-10-14',
            'text' => 'Objednal jsem dveře jako vánoční dárek. Přišly včas a rodina je nadšená.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Milada N.',
            'city' => 'Karviná',
            'stars' => 5,
            'date' => '2024-10-24',
            'text' => 'Objednala jsem posuvné dveře do kuchyně. Ušetřily místo a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Jaromír B.',
            'city' => 'Znojmo',
            'stars' => 4,
            'date' => '2024-11-03',
            'text' => 'Objednal jsem bez montáže, ale zasekl jsem se u kotvení. Zavolal jsem jim a poradili mi. Zvládl jsem to nakonec sám.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Stanislava K.',
            'city' => 'Chomutov',
            'stars' => 5,
            'date' => '2024-11-14',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Vladimír N.',
            'city' => 'Kolín',
            'stars' => 5,
            'date' => '2024-11-24',
            'text' => 'Objednal jsem sprchový kout. Koupelna vypadá moderně. Doporučuju.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Libuše B.',
            'city' => 'Mladá Boleslav',
            'stars' => 5,
            'date' => '2024-12-04',
            'text' => 'Objednala jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Drahomíra K.',
            'city' => 'Přerov',
            'stars' => 5,
            'date' => '2024-12-14',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Alois B.',
            'city' => 'Ústí nad Labem',
            'stars' => 5,
            'date' => '2024-12-24',
            'text' => 'Objednal jsem zábradlí na schodiště. Montáž jsem zvládl sám. Schodiště vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Jaroslava N.',
            'city' => 'Frýdek-Místek',
            'stars' => 4,
            'date' => '2025-01-03',
            'text' => 'Dodací lhůta byla delší než jsem čekala. Napsala jsem jim a omluvili se. Dveře jsou kvalitní.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radovan K.',
            'city' => 'Havířov',
            'stars' => 5,
            'date' => '2025-01-13',
            'text' => 'Objednal jsem bez montáže, ale pak jsem zjistil že na to nestačím. Zavolal jsem jim a domluvili jsme montáž dodatečně. Kluci přijeli a bylo to rychlé.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Milena N.',
            'city' => 'Most',
            'stars' => 5,
            'date' => '2025-01-23',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Cyril B.',
            'city' => 'Teplice',
            'stars' => 5,
            'date' => '2025-02-02',
            'text' => 'Objednal jsem sprchový kout walk-in. Koupelna vypadá moderně a prostorně.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Světlana N.',
            'city' => 'Děčín',
            'stars' => 5,
            'date' => '2025-02-12',
            'text' => 'Objednala jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Lumír B.',
            'city' => 'Jablonec nad Nisou',
            'stars' => 4,
            'date' => '2025-02-22',
            'text' => 'Po montáži mi dveře trochu drhnuly. Napsal jsem jim a poradili mi jak seřídit. Zvládl jsem to sám.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Štěpánka K.',
            'city' => 'Prostějov',
            'stars' => 5,
            'date' => '2025-03-04',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Evžen N.',
            'city' => 'Kroměříž',
            'stars' => 5,
            'date' => '2025-03-15',
            'text' => 'Objednal jsem zábradlí na balkon. Montáž jsem zvládl sám. Balkon vypadá moderně.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Kateřina B.',
            'city' => 'Uherské Hradiště',
            'stars' => 5,
            'date' => '2025-03-25',
            'text' => 'Objednala jsem sprchový kout. Koupelna vypadá skvěle a montáž proběhla hladce.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Augustin K.',
            'city' => 'Vsetín',
            'stars' => 5,
            'date' => '2025-04-04',
            'text' => 'Objednal jsem dveře do pracovny. Přišly v pořádku a pracovna vypadá profesionálně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Růžena B.',
            'city' => 'Valašské Meziříčí',
            'stars' => 4,
            'date' => '2025-04-14',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Vyfotila jsem to a napsala jim. Do týdne mi poslali náhradu.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ladislav N.',
            'city' => 'Nový Jičín',
            'stars' => 5,
            'date' => '2025-04-24',
            'text' => 'Objednal jsem posuvné dveře do kuchyně. Ušetřily místo a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Marta B.',
            'city' => 'Třinec',
            'stars' => 5,
            'date' => '2025-05-04',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Zdeněk K.',
            'city' => 'Brno',
            'stars' => 5,
            'date' => '2025-05-14',
            'text' => 'Objednal jsem dveře jako vánoční dárek. Přišly včas a manželka je nadšená.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Irena B.',
            'city' => 'Praha',
            'stars' => 5,
            'date' => '2025-05-24',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle. Ložnice se proměnila.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ctibor N.',
            'city' => 'Ostrava',
            'stars' => 4,
            'date' => '2025-06-03',
            'text' => 'Objednal jsem bez montáže a zasekl jsem se u kotvení. Zavolal jsem jim a poradili mi. Zvládl jsem to nakonec sám.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Božena K.',
            'city' => 'Plzeň',
            'stars' => 5,
            'date' => '2025-06-13',
            'text' => 'Objednala jsem sprchový kout walk-in. Koupelna vypadá skvěle.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Přemysl B.',
            'city' => 'Liberec',
            'stars' => 5,
            'date' => '2025-06-23',
            'text' => 'Objednal jsem zábradlí na schodiště. Montáž jsem zvládl sám. Schodiště vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Věnceslava B.',
            'city' => 'Olomouc',
            'stars' => 5,
            'date' => '2025-07-04',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Miroslav N.',
            'city' => 'Zlín',
            'stars' => 5,
            'date' => '2025-07-14',
            'text' => 'Objednal jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Anežka K.',
            'city' => 'Pardubice',
            'stars' => 4,
            'date' => '2025-07-24',
            'text' => 'Po montáži mi dveře trochu skřípaly. Napsal jsem jim a poradili mi jak seřídit. Zvládla jsem to sama.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Bohumil B.',
            'city' => 'Hradec Králové',
            'stars' => 5,
            'date' => '2025-08-03',
            'text' => 'Objednal jsem sprchový kout. Koupelna vypadá moderně. Doporučuju.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Taťána K.',
            'city' => 'Jihlava',
            'stars' => 5,
            'date' => '2025-08-13',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radoslav K.',
            'city' => 'Tábor',
            'stars' => 5,
            'date' => '2025-08-23',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Výsledek je skvělý.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Milada B.',
            'city' => 'Kladno',
            'stars' => 5,
            'date' => '2025-09-02',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Jaromír N.',
            'city' => 'Opava',
            'stars' => 4,
            'date' => '2025-09-12',
            'text' => 'Dodací lhůta byla trochu delší. Napsala jsem jim a omluvili se. Dveře jsou kvalitní.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Stanislava B.',
            'city' => 'Karviná',
            'stars' => 5,
            'date' => '2025-09-22',
            'text' => 'Objednala jsem posuvné dveře do kuchyně. Ušetřily místo a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Vladimír K.',
            'city' => 'Znojmo',
            'stars' => 5,
            'date' => '2025-10-02',
            'text' => 'Objednal jsem dveře a zábradlí najednou. Oboje přišlo v pořádku. Dům vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Libuše N.',
            'city' => 'Chomutov',
            'stars' => 5,
            'date' => '2025-10-12',
            'text' => 'Objednala jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Drahomíra B.',
            'city' => 'Kolín',
            'stars' => 5,
            'date' => '2025-10-23',
            'text' => 'Objednala jsem sprchový kout walk-in. Koupelna vypadá moderně a prostorně.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Alois K.',
            'city' => 'Mladá Boleslav',
            'stars' => 5,
            'date' => '2025-11-02',
            'text' => 'Objednal jsem zábradlí na balkon. Montáž jsem zvládl sám. Balkon vypadá moderně.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Jaroslava B.',
            'city' => 'Přerov',
            'stars' => 4,
            'date' => '2025-11-12',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Vyfotila jsem to a napsala jim. Do týdne mi poslali náhradu.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radovan B.',
            'city' => 'Ústí nad Labem',
            'stars' => 5,
            'date' => '2025-11-22',
            'text' => 'Objednal jsem bez montáže, ale pak jsem zjistil že na to nestačím. Zavolal jsem jim a domluvili jsme montáž dodatečně. Kluci přijeli a bylo to rychlé.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Milena K.',
            'city' => 'Frýdek-Místek',
            'stars' => 5,
            'date' => '2025-12-02',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Cyril K.',
            'city' => 'Havířov',
            'stars' => 5,
            'date' => '2025-12-12',
            'text' => 'Objednal jsem dveře jako vánoční dárek. Přišly včas a rodina je nadšená.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Světlana B.',
            'city' => 'Most',
            'stars' => 5,
            'date' => '2025-12-22',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Lumír N.',
            'city' => 'Teplice',
            'stars' => 4,
            'date' => '2026-01-01',
            'text' => 'Po montáži mi dveře trochu drhnuly. Napsal jsem jim a poradili mi jak seřídit. Zvládl jsem to sám.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Štěpánka B.',
            'city' => 'Děčín',
            'stars' => 5,
            'date' => '2026-01-11',
            'text' => 'Objednala jsem sprchový kout. Koupelna vypadá skvěle a montáž proběhla hladce.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Evžen K.',
            'city' => 'Jablonec nad Nisou',
            'stars' => 5,
            'date' => '2026-01-21',
            'text' => 'Objednal jsem posuvné dveře do obýváku. Ušetřily místo a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Kateřina N.',
            'city' => 'Prostějov',
            'stars' => 5,
            'date' => '2026-01-31',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Augustin N.',
            'city' => 'Kroměříž',
            'stars' => 5,
            'date' => '2026-02-10',
            'text' => 'Objednal jsem zábradlí na schodiště. Montáž jsem zvládl sám. Schodiště vypadá skvěle.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Růžena K.',
            'city' => 'Uherské Hradiště',
            'stars' => 4,
            'date' => '2026-02-21',
            'text' => 'Objednala jsem bez montáže, ale pak jsem zjistila že na to nestačím. Zavolala jsem jim a domluvily jsme montáž dodatečně. Kluci přijeli a bylo to rychlé.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Ladislav B.',
            'city' => 'Vsetín',
            'stars' => 5,
            'date' => '2026-03-03',
            'text' => 'Objednal jsem dveře do pracovny. Přišly v pořádku a pracovna vypadá profesionálně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Marta K.',
            'city' => 'Valašské Meziříčí',
            'stars' => 5,
            'date' => '2026-03-13',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Zdeněk N.',
            'city' => 'Nový Jičín',
            'stars' => 5,
            'date' => '2026-03-23',
            'text' => 'Objednal jsem sprchový kout walk-in. Koupelna vypadá moderně a prostorně.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Irena K.',
            'city' => 'Třinec',
            'stars' => 5,
            'date' => '2026-04-02',
            'text' => 'Objednala jsem dveře do obýváku. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Ctibor B.',
            'city' => 'Brno',
            'stars' => 4,
            'date' => '2026-04-12',
            'text' => 'Přišly mi dveře s malými škrábanci na skle. Vyfotil jsem to a napsala jim. Do týdne mi poslali náhradu. Spokojený jsem.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Božena N.',
            'city' => 'Praha',
            'stars' => 5,
            'date' => '2026-04-22',
            'text' => 'Objednala jsem dveře do koupelny. Přišly v pořádku a vypadají skvěle. Koupelna se proměnila.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Přemysl K.',
            'city' => 'Ostrava',
            'stars' => 5,
            'date' => '2026-05-02',
            'text' => 'Objednal jsem zábradlí na balkon. Montáž jsem zvládl sám. Balkon vypadá moderně.',
            'category' => 'zabradli',
        ],
        [
            'name' => 'Věnceslava K.',
            'city' => 'Plzeň',
            'stars' => 5,
            'date' => '2026-05-12',
            'text' => 'Objednala jsem sprchový kout. Koupelna vypadá skvěle.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Miroslav B.',
            'city' => 'Liberec',
            'stars' => 5,
            'date' => '2026-05-22',
            'text' => 'Objednal jsem dveře do pracovny. Přišly v pořádku a pracovna vypadá profesionálně.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Anežka N.',
            'city' => 'Olomouc',
            'stars' => 4,
            'date' => '2026-06-01',
            'text' => 'Dodací lhůta byla delší než jsem čekala. Napsala jsem jim a omluvili se. Dveře jsou kvalitní.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Bohumil K.',
            'city' => 'Zlín',
            'stars' => 5,
            'date' => '2026-06-12',
            'text' => 'Objednal jsem dveře a sprchový kout najednou. Oboje přišlo v pořádku a vypadá skvěle.',
            'category' => 'sprcha',
        ],
        [
            'name' => 'Taťána N.',
            'city' => 'Pardubice',
            'stars' => 5,
            'date' => '2026-06-22',
            'text' => 'Objednala jsem posuvné dveře do kuchyně. Ušetřily místo a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Radoslav N.',
            'city' => 'Hradec Králové',
            'stars' => 5,
            'date' => '2026-07-02',
            'text' => 'Objednal jsem bez montáže a zvládl jsem to sám. Výsledek je skvělý.',
            'category' => 'ostatni',
        ],
        [
            'name' => 'Milada K.',
            'city' => 'Jihlava',
            'stars' => 5,
            'date' => '2026-07-12',
            'text' => 'Objednala jsem dveře do ložnice. Přišly v pořádku a vypadají skvěle.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Jaromír N.',
            'city' => 'Tábor',
            'stars' => 4,
            'date' => '2026-07-22',
            'text' => 'Po montáži mi dveře trochu skřípaly. Napsal jsem jim a poradili mi jak seřídit. Zvládl jsem to sám.',
            'category' => 'dvere',
        ],
        [
            'name' => 'Stanislava N.',
            'city' => 'Kladno',
            'stars' => 5,
            'date' => '2026-08-01',
            'text' => 'Objednala jsem dveře jako vánoční dárek. Přišly včas a manžel je nadšený.',
            'category' => 'dvere',
        ],
    ];

    return $cache;
}

/** @return array{count:int,avg:float,sum:int} */
function sklo_recenze_stats(): array
{
    $all = sklo_recenze_all();
    $sum = 0;
    foreach ($all as $r) {
        $sum += (int) $r['stars'];
    }
    $count = count($all);
    $avg = $count > 0 ? round($sum / $count, 1) : 0.0;
    return ['count' => $count, 'avg' => $avg, 'sum' => $sum];
}

/**
 * @return list<array{name:string,city:string,stars:int,date:string,text:string,category:string}>
 */
function sklo_recenze_featured(int $limit = 8): array
{
    $all = sklo_recenze_all();
    $five = array_values(array_filter($all, static fn($r) => (int) $r['stars'] === 5));
    // Spread featured picks across the timeline for variety.
    $n = count($five);
    if ($n === 0) {
        return array_slice($all, 0, $limit);
    }
    $picks = [];
    for ($i = 0; $i < $limit; $i++) {
        $idx = (int) round($i * ($n - 1) / max(1, $limit - 1));
        $picks[] = $five[$idx];
    }
    return $picks;
}
